// Copyright Rivtower Technologies LLC.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This file is generated by rust-protobuf 2.8.1. Do not edit
// @generated

// https://github.com/Manishearth/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![cfg_attr(rustfmt, rustfmt_skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unsafe_code)]
#![allow(unused_imports)]
#![allow(unused_results)]
//! Generated file from `auth.proto`

use protobuf::Message as Message_imported_for_functions;
use protobuf::ProtobufEnum as ProtobufEnum_imported_for_functions;

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_2_8_1;

#[derive(PartialEq,Clone,Default)]
pub struct VerifyTxReq {
    // message fields
    pub valid_until_block: u64,
    pub hash: ::std::vec::Vec<u8>,
    pub signature: ::std::vec::Vec<u8>,
    pub crypto: super::blockchain::Crypto,
    pub tx_hash: ::std::vec::Vec<u8>,
    pub signer: ::std::vec::Vec<u8>,
    pub nonce: ::std::string::String,
    pub chain_id: u32,
    pub quota: u64,
    pub value: ::std::vec::Vec<u8>,
    pub chain_id_v1: ::std::vec::Vec<u8>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a VerifyTxReq {
    fn default() -> &'a VerifyTxReq {
        <VerifyTxReq as ::protobuf::Message>::default_instance()
    }
}

impl VerifyTxReq {
    pub fn new() -> VerifyTxReq {
        ::std::default::Default::default()
    }

    // uint64 valid_until_block = 1;


    pub fn get_valid_until_block(&self) -> u64 {
        self.valid_until_block
    }
    pub fn clear_valid_until_block(&mut self) {
        self.valid_until_block = 0;
    }

    // Param is passed by value, moved
    pub fn set_valid_until_block(&mut self, v: u64) {
        self.valid_until_block = v;
    }

    // bytes hash = 2;


    pub fn get_hash(&self) -> &[u8] {
        &self.hash
    }
    pub fn clear_hash(&mut self) {
        self.hash.clear();
    }

    // Param is passed by value, moved
    pub fn set_hash(&mut self, v: ::std::vec::Vec<u8>) {
        self.hash = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_hash(&mut self) -> &mut ::std::vec::Vec<u8> {
        &mut self.hash
    }

    // Take field
    pub fn take_hash(&mut self) -> ::std::vec::Vec<u8> {
        ::std::mem::replace(&mut self.hash, ::std::vec::Vec::new())
    }

    // bytes signature = 3;


    pub fn get_signature(&self) -> &[u8] {
        &self.signature
    }
    pub fn clear_signature(&mut self) {
        self.signature.clear();
    }

    // Param is passed by value, moved
    pub fn set_signature(&mut self, v: ::std::vec::Vec<u8>) {
        self.signature = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_signature(&mut self) -> &mut ::std::vec::Vec<u8> {
        &mut self.signature
    }

    // Take field
    pub fn take_signature(&mut self) -> ::std::vec::Vec<u8> {
        ::std::mem::replace(&mut self.signature, ::std::vec::Vec::new())
    }

    // .Crypto crypto = 4;


    pub fn get_crypto(&self) -> super::blockchain::Crypto {
        self.crypto
    }
    pub fn clear_crypto(&mut self) {
        self.crypto = super::blockchain::Crypto::DEFAULT;
    }

    // Param is passed by value, moved
    pub fn set_crypto(&mut self, v: super::blockchain::Crypto) {
        self.crypto = v;
    }

    // bytes tx_hash = 5;


    pub fn get_tx_hash(&self) -> &[u8] {
        &self.tx_hash
    }
    pub fn clear_tx_hash(&mut self) {
        self.tx_hash.clear();
    }

    // Param is passed by value, moved
    pub fn set_tx_hash(&mut self, v: ::std::vec::Vec<u8>) {
        self.tx_hash = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_tx_hash(&mut self) -> &mut ::std::vec::Vec<u8> {
        &mut self.tx_hash
    }

    // Take field
    pub fn take_tx_hash(&mut self) -> ::std::vec::Vec<u8> {
        ::std::mem::replace(&mut self.tx_hash, ::std::vec::Vec::new())
    }

    // bytes signer = 6;


    pub fn get_signer(&self) -> &[u8] {
        &self.signer
    }
    pub fn clear_signer(&mut self) {
        self.signer.clear();
    }

    // Param is passed by value, moved
    pub fn set_signer(&mut self, v: ::std::vec::Vec<u8>) {
        self.signer = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_signer(&mut self) -> &mut ::std::vec::Vec<u8> {
        &mut self.signer
    }

    // Take field
    pub fn take_signer(&mut self) -> ::std::vec::Vec<u8> {
        ::std::mem::replace(&mut self.signer, ::std::vec::Vec::new())
    }

    // string nonce = 7;


    pub fn get_nonce(&self) -> &str {
        &self.nonce
    }
    pub fn clear_nonce(&mut self) {
        self.nonce.clear();
    }

    // Param is passed by value, moved
    pub fn set_nonce(&mut self, v: ::std::string::String) {
        self.nonce = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_nonce(&mut self) -> &mut ::std::string::String {
        &mut self.nonce
    }

    // Take field
    pub fn take_nonce(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.nonce, ::std::string::String::new())
    }

    // uint32 chain_id = 8;


    pub fn get_chain_id(&self) -> u32 {
        self.chain_id
    }
    pub fn clear_chain_id(&mut self) {
        self.chain_id = 0;
    }

    // Param is passed by value, moved
    pub fn set_chain_id(&mut self, v: u32) {
        self.chain_id = v;
    }

    // uint64 quota = 9;


    pub fn get_quota(&self) -> u64 {
        self.quota
    }
    pub fn clear_quota(&mut self) {
        self.quota = 0;
    }

    // Param is passed by value, moved
    pub fn set_quota(&mut self, v: u64) {
        self.quota = v;
    }

    // bytes value = 10;


    pub fn get_value(&self) -> &[u8] {
        &self.value
    }
    pub fn clear_value(&mut self) {
        self.value.clear();
    }

    // Param is passed by value, moved
    pub fn set_value(&mut self, v: ::std::vec::Vec<u8>) {
        self.value = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_value(&mut self) -> &mut ::std::vec::Vec<u8> {
        &mut self.value
    }

    // Take field
    pub fn take_value(&mut self) -> ::std::vec::Vec<u8> {
        ::std::mem::replace(&mut self.value, ::std::vec::Vec::new())
    }

    // bytes chain_id_v1 = 11;


    pub fn get_chain_id_v1(&self) -> &[u8] {
        &self.chain_id_v1
    }
    pub fn clear_chain_id_v1(&mut self) {
        self.chain_id_v1.clear();
    }

    // Param is passed by value, moved
    pub fn set_chain_id_v1(&mut self, v: ::std::vec::Vec<u8>) {
        self.chain_id_v1 = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_chain_id_v1(&mut self) -> &mut ::std::vec::Vec<u8> {
        &mut self.chain_id_v1
    }

    // Take field
    pub fn take_chain_id_v1(&mut self) -> ::std::vec::Vec<u8> {
        ::std::mem::replace(&mut self.chain_id_v1, ::std::vec::Vec::new())
    }
}

impl ::protobuf::Message for VerifyTxReq {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint64()?;
                    self.valid_until_block = tmp;
                },
                2 => {
                    ::protobuf::rt::read_singular_proto3_bytes_into(wire_type, is, &mut self.hash)?;
                },
                3 => {
                    ::protobuf::rt::read_singular_proto3_bytes_into(wire_type, is, &mut self.signature)?;
                },
                4 => {
                    ::protobuf::rt::read_proto3_enum_with_unknown_fields_into(wire_type, is, &mut self.crypto, 4, &mut self.unknown_fields)?
                },
                5 => {
                    ::protobuf::rt::read_singular_proto3_bytes_into(wire_type, is, &mut self.tx_hash)?;
                },
                6 => {
                    ::protobuf::rt::read_singular_proto3_bytes_into(wire_type, is, &mut self.signer)?;
                },
                7 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.nonce)?;
                },
                8 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint32()?;
                    self.chain_id = tmp;
                },
                9 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint64()?;
                    self.quota = tmp;
                },
                10 => {
                    ::protobuf::rt::read_singular_proto3_bytes_into(wire_type, is, &mut self.value)?;
                },
                11 => {
                    ::protobuf::rt::read_singular_proto3_bytes_into(wire_type, is, &mut self.chain_id_v1)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if self.valid_until_block != 0 {
            my_size += ::protobuf::rt::value_size(1, self.valid_until_block, ::protobuf::wire_format::WireTypeVarint);
        }
        if !self.hash.is_empty() {
            my_size += ::protobuf::rt::bytes_size(2, &self.hash);
        }
        if !self.signature.is_empty() {
            my_size += ::protobuf::rt::bytes_size(3, &self.signature);
        }
        if self.crypto != super::blockchain::Crypto::DEFAULT {
            my_size += ::protobuf::rt::enum_size(4, self.crypto);
        }
        if !self.tx_hash.is_empty() {
            my_size += ::protobuf::rt::bytes_size(5, &self.tx_hash);
        }
        if !self.signer.is_empty() {
            my_size += ::protobuf::rt::bytes_size(6, &self.signer);
        }
        if !self.nonce.is_empty() {
            my_size += ::protobuf::rt::string_size(7, &self.nonce);
        }
        if self.chain_id != 0 {
            my_size += ::protobuf::rt::value_size(8, self.chain_id, ::protobuf::wire_format::WireTypeVarint);
        }
        if self.quota != 0 {
            my_size += ::protobuf::rt::value_size(9, self.quota, ::protobuf::wire_format::WireTypeVarint);
        }
        if !self.value.is_empty() {
            my_size += ::protobuf::rt::bytes_size(10, &self.value);
        }
        if !self.chain_id_v1.is_empty() {
            my_size += ::protobuf::rt::bytes_size(11, &self.chain_id_v1);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if self.valid_until_block != 0 {
            os.write_uint64(1, self.valid_until_block)?;
        }
        if !self.hash.is_empty() {
            os.write_bytes(2, &self.hash)?;
        }
        if !self.signature.is_empty() {
            os.write_bytes(3, &self.signature)?;
        }
        if self.crypto != super::blockchain::Crypto::DEFAULT {
            os.write_enum(4, self.crypto.value())?;
        }
        if !self.tx_hash.is_empty() {
            os.write_bytes(5, &self.tx_hash)?;
        }
        if !self.signer.is_empty() {
            os.write_bytes(6, &self.signer)?;
        }
        if !self.nonce.is_empty() {
            os.write_string(7, &self.nonce)?;
        }
        if self.chain_id != 0 {
            os.write_uint32(8, self.chain_id)?;
        }
        if self.quota != 0 {
            os.write_uint64(9, self.quota)?;
        }
        if !self.value.is_empty() {
            os.write_bytes(10, &self.value)?;
        }
        if !self.chain_id_v1.is_empty() {
            os.write_bytes(11, &self.chain_id_v1)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> VerifyTxReq {
        VerifyTxReq::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint64>(
                    "valid_until_block",
                    |m: &VerifyTxReq| { &m.valid_until_block },
                    |m: &mut VerifyTxReq| { &mut m.valid_until_block },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeBytes>(
                    "hash",
                    |m: &VerifyTxReq| { &m.hash },
                    |m: &mut VerifyTxReq| { &mut m.hash },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeBytes>(
                    "signature",
                    |m: &VerifyTxReq| { &m.signature },
                    |m: &mut VerifyTxReq| { &mut m.signature },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeEnum<super::blockchain::Crypto>>(
                    "crypto",
                    |m: &VerifyTxReq| { &m.crypto },
                    |m: &mut VerifyTxReq| { &mut m.crypto },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeBytes>(
                    "tx_hash",
                    |m: &VerifyTxReq| { &m.tx_hash },
                    |m: &mut VerifyTxReq| { &mut m.tx_hash },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeBytes>(
                    "signer",
                    |m: &VerifyTxReq| { &m.signer },
                    |m: &mut VerifyTxReq| { &mut m.signer },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "nonce",
                    |m: &VerifyTxReq| { &m.nonce },
                    |m: &mut VerifyTxReq| { &mut m.nonce },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint32>(
                    "chain_id",
                    |m: &VerifyTxReq| { &m.chain_id },
                    |m: &mut VerifyTxReq| { &mut m.chain_id },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint64>(
                    "quota",
                    |m: &VerifyTxReq| { &m.quota },
                    |m: &mut VerifyTxReq| { &mut m.quota },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeBytes>(
                    "value",
                    |m: &VerifyTxReq| { &m.value },
                    |m: &mut VerifyTxReq| { &mut m.value },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeBytes>(
                    "chain_id_v1",
                    |m: &VerifyTxReq| { &m.chain_id_v1 },
                    |m: &mut VerifyTxReq| { &mut m.chain_id_v1 },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<VerifyTxReq>(
                    "VerifyTxReq",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static VerifyTxReq {
        static mut instance: ::protobuf::lazy::Lazy<VerifyTxReq> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const VerifyTxReq,
        };
        unsafe {
            instance.get(VerifyTxReq::new)
        }
    }
}

impl ::protobuf::Clear for VerifyTxReq {
    fn clear(&mut self) {
        self.valid_until_block = 0;
        self.hash.clear();
        self.signature.clear();
        self.crypto = super::blockchain::Crypto::DEFAULT;
        self.tx_hash.clear();
        self.signer.clear();
        self.nonce.clear();
        self.chain_id = 0;
        self.quota = 0;
        self.value.clear();
        self.chain_id_v1.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for VerifyTxReq {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for VerifyTxReq {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct VerifyBlockReq {
    // message fields
    pub height: u64,
    pub round: u64,
    pub block: ::protobuf::SingularPtrField<super::blockchain::CompactBlock>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a VerifyBlockReq {
    fn default() -> &'a VerifyBlockReq {
        <VerifyBlockReq as ::protobuf::Message>::default_instance()
    }
}

impl VerifyBlockReq {
    pub fn new() -> VerifyBlockReq {
        ::std::default::Default::default()
    }

    // uint64 height = 1;


    pub fn get_height(&self) -> u64 {
        self.height
    }
    pub fn clear_height(&mut self) {
        self.height = 0;
    }

    // Param is passed by value, moved
    pub fn set_height(&mut self, v: u64) {
        self.height = v;
    }

    // uint64 round = 2;


    pub fn get_round(&self) -> u64 {
        self.round
    }
    pub fn clear_round(&mut self) {
        self.round = 0;
    }

    // Param is passed by value, moved
    pub fn set_round(&mut self, v: u64) {
        self.round = v;
    }

    // .CompactBlock block = 3;


    pub fn get_block(&self) -> &super::blockchain::CompactBlock {
        self.block.as_ref().unwrap_or_else(|| super::blockchain::CompactBlock::default_instance())
    }
    pub fn clear_block(&mut self) {
        self.block.clear();
    }

    pub fn has_block(&self) -> bool {
        self.block.is_some()
    }

    // Param is passed by value, moved
    pub fn set_block(&mut self, v: super::blockchain::CompactBlock) {
        self.block = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_block(&mut self) -> &mut super::blockchain::CompactBlock {
        if self.block.is_none() {
            self.block.set_default();
        }
        self.block.as_mut().unwrap()
    }

    // Take field
    pub fn take_block(&mut self) -> super::blockchain::CompactBlock {
        self.block.take().unwrap_or_else(|| super::blockchain::CompactBlock::new())
    }
}

impl ::protobuf::Message for VerifyBlockReq {
    fn is_initialized(&self) -> bool {
        for v in &self.block {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint64()?;
                    self.height = tmp;
                },
                2 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint64()?;
                    self.round = tmp;
                },
                3 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.block)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if self.height != 0 {
            my_size += ::protobuf::rt::value_size(1, self.height, ::protobuf::wire_format::WireTypeVarint);
        }
        if self.round != 0 {
            my_size += ::protobuf::rt::value_size(2, self.round, ::protobuf::wire_format::WireTypeVarint);
        }
        if let Some(ref v) = self.block.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if self.height != 0 {
            os.write_uint64(1, self.height)?;
        }
        if self.round != 0 {
            os.write_uint64(2, self.round)?;
        }
        if let Some(ref v) = self.block.as_ref() {
            os.write_tag(3, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> VerifyBlockReq {
        VerifyBlockReq::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint64>(
                    "height",
                    |m: &VerifyBlockReq| { &m.height },
                    |m: &mut VerifyBlockReq| { &mut m.height },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint64>(
                    "round",
                    |m: &VerifyBlockReq| { &m.round },
                    |m: &mut VerifyBlockReq| { &mut m.round },
                ));
                fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<super::blockchain::CompactBlock>>(
                    "block",
                    |m: &VerifyBlockReq| { &m.block },
                    |m: &mut VerifyBlockReq| { &mut m.block },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<VerifyBlockReq>(
                    "VerifyBlockReq",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static VerifyBlockReq {
        static mut instance: ::protobuf::lazy::Lazy<VerifyBlockReq> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const VerifyBlockReq,
        };
        unsafe {
            instance.get(VerifyBlockReq::new)
        }
    }
}

impl ::protobuf::Clear for VerifyBlockReq {
    fn clear(&mut self) {
        self.height = 0;
        self.round = 0;
        self.block.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for VerifyBlockReq {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for VerifyBlockReq {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct VerifyBlockResp {
    // message fields
    pub height: u64,
    pub round: u64,
    pub pass: bool,
    pub block: ::protobuf::SingularPtrField<super::blockchain::Block>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a VerifyBlockResp {
    fn default() -> &'a VerifyBlockResp {
        <VerifyBlockResp as ::protobuf::Message>::default_instance()
    }
}

impl VerifyBlockResp {
    pub fn new() -> VerifyBlockResp {
        ::std::default::Default::default()
    }

    // uint64 height = 1;


    pub fn get_height(&self) -> u64 {
        self.height
    }
    pub fn clear_height(&mut self) {
        self.height = 0;
    }

    // Param is passed by value, moved
    pub fn set_height(&mut self, v: u64) {
        self.height = v;
    }

    // uint64 round = 2;


    pub fn get_round(&self) -> u64 {
        self.round
    }
    pub fn clear_round(&mut self) {
        self.round = 0;
    }

    // Param is passed by value, moved
    pub fn set_round(&mut self, v: u64) {
        self.round = v;
    }

    // bool pass = 3;


    pub fn get_pass(&self) -> bool {
        self.pass
    }
    pub fn clear_pass(&mut self) {
        self.pass = false;
    }

    // Param is passed by value, moved
    pub fn set_pass(&mut self, v: bool) {
        self.pass = v;
    }

    // .Block block = 4;


    pub fn get_block(&self) -> &super::blockchain::Block {
        self.block.as_ref().unwrap_or_else(|| super::blockchain::Block::default_instance())
    }
    pub fn clear_block(&mut self) {
        self.block.clear();
    }

    pub fn has_block(&self) -> bool {
        self.block.is_some()
    }

    // Param is passed by value, moved
    pub fn set_block(&mut self, v: super::blockchain::Block) {
        self.block = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_block(&mut self) -> &mut super::blockchain::Block {
        if self.block.is_none() {
            self.block.set_default();
        }
        self.block.as_mut().unwrap()
    }

    // Take field
    pub fn take_block(&mut self) -> super::blockchain::Block {
        self.block.take().unwrap_or_else(|| super::blockchain::Block::new())
    }
}

impl ::protobuf::Message for VerifyBlockResp {
    fn is_initialized(&self) -> bool {
        for v in &self.block {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint64()?;
                    self.height = tmp;
                },
                2 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint64()?;
                    self.round = tmp;
                },
                3 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_bool()?;
                    self.pass = tmp;
                },
                4 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.block)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if self.height != 0 {
            my_size += ::protobuf::rt::value_size(1, self.height, ::protobuf::wire_format::WireTypeVarint);
        }
        if self.round != 0 {
            my_size += ::protobuf::rt::value_size(2, self.round, ::protobuf::wire_format::WireTypeVarint);
        }
        if self.pass != false {
            my_size += 2;
        }
        if let Some(ref v) = self.block.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if self.height != 0 {
            os.write_uint64(1, self.height)?;
        }
        if self.round != 0 {
            os.write_uint64(2, self.round)?;
        }
        if self.pass != false {
            os.write_bool(3, self.pass)?;
        }
        if let Some(ref v) = self.block.as_ref() {
            os.write_tag(4, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> VerifyBlockResp {
        VerifyBlockResp::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint64>(
                    "height",
                    |m: &VerifyBlockResp| { &m.height },
                    |m: &mut VerifyBlockResp| { &mut m.height },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint64>(
                    "round",
                    |m: &VerifyBlockResp| { &m.round },
                    |m: &mut VerifyBlockResp| { &mut m.round },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeBool>(
                    "pass",
                    |m: &VerifyBlockResp| { &m.pass },
                    |m: &mut VerifyBlockResp| { &mut m.pass },
                ));
                fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<super::blockchain::Block>>(
                    "block",
                    |m: &VerifyBlockResp| { &m.block },
                    |m: &mut VerifyBlockResp| { &mut m.block },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<VerifyBlockResp>(
                    "VerifyBlockResp",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static VerifyBlockResp {
        static mut instance: ::protobuf::lazy::Lazy<VerifyBlockResp> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const VerifyBlockResp,
        };
        unsafe {
            instance.get(VerifyBlockResp::new)
        }
    }
}

impl ::protobuf::Clear for VerifyBlockResp {
    fn clear(&mut self) {
        self.height = 0;
        self.round = 0;
        self.pass = false;
        self.block.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for VerifyBlockResp {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for VerifyBlockResp {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct BlockTxHashes {
    // message fields
    pub height: u64,
    pub tx_hashes: ::protobuf::RepeatedField<::std::vec::Vec<u8>>,
    pub block_quota_limit: u64,
    pub account_quota_limit: ::protobuf::SingularPtrField<super::blockchain::AccountGasLimit>,
    pub check_quota: bool,
    pub admin_address: ::std::vec::Vec<u8>,
    pub version: u32,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a BlockTxHashes {
    fn default() -> &'a BlockTxHashes {
        <BlockTxHashes as ::protobuf::Message>::default_instance()
    }
}

impl BlockTxHashes {
    pub fn new() -> BlockTxHashes {
        ::std::default::Default::default()
    }

    // uint64 height = 1;


    pub fn get_height(&self) -> u64 {
        self.height
    }
    pub fn clear_height(&mut self) {
        self.height = 0;
    }

    // Param is passed by value, moved
    pub fn set_height(&mut self, v: u64) {
        self.height = v;
    }

    // repeated bytes tx_hashes = 2;


    pub fn get_tx_hashes(&self) -> &[::std::vec::Vec<u8>] {
        &self.tx_hashes
    }
    pub fn clear_tx_hashes(&mut self) {
        self.tx_hashes.clear();
    }

    // Param is passed by value, moved
    pub fn set_tx_hashes(&mut self, v: ::protobuf::RepeatedField<::std::vec::Vec<u8>>) {
        self.tx_hashes = v;
    }

    // Mutable pointer to the field.
    pub fn mut_tx_hashes(&mut self) -> &mut ::protobuf::RepeatedField<::std::vec::Vec<u8>> {
        &mut self.tx_hashes
    }

    // Take field
    pub fn take_tx_hashes(&mut self) -> ::protobuf::RepeatedField<::std::vec::Vec<u8>> {
        ::std::mem::replace(&mut self.tx_hashes, ::protobuf::RepeatedField::new())
    }

    // uint64 block_quota_limit = 3;


    pub fn get_block_quota_limit(&self) -> u64 {
        self.block_quota_limit
    }
    pub fn clear_block_quota_limit(&mut self) {
        self.block_quota_limit = 0;
    }

    // Param is passed by value, moved
    pub fn set_block_quota_limit(&mut self, v: u64) {
        self.block_quota_limit = v;
    }

    // .AccountGasLimit account_quota_limit = 4;


    pub fn get_account_quota_limit(&self) -> &super::blockchain::AccountGasLimit {
        self.account_quota_limit.as_ref().unwrap_or_else(|| super::blockchain::AccountGasLimit::default_instance())
    }
    pub fn clear_account_quota_limit(&mut self) {
        self.account_quota_limit.clear();
    }

    pub fn has_account_quota_limit(&self) -> bool {
        self.account_quota_limit.is_some()
    }

    // Param is passed by value, moved
    pub fn set_account_quota_limit(&mut self, v: super::blockchain::AccountGasLimit) {
        self.account_quota_limit = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_account_quota_limit(&mut self) -> &mut super::blockchain::AccountGasLimit {
        if self.account_quota_limit.is_none() {
            self.account_quota_limit.set_default();
        }
        self.account_quota_limit.as_mut().unwrap()
    }

    // Take field
    pub fn take_account_quota_limit(&mut self) -> super::blockchain::AccountGasLimit {
        self.account_quota_limit.take().unwrap_or_else(|| super::blockchain::AccountGasLimit::new())
    }

    // bool check_quota = 5;


    pub fn get_check_quota(&self) -> bool {
        self.check_quota
    }
    pub fn clear_check_quota(&mut self) {
        self.check_quota = false;
    }

    // Param is passed by value, moved
    pub fn set_check_quota(&mut self, v: bool) {
        self.check_quota = v;
    }

    // bytes admin_address = 6;


    pub fn get_admin_address(&self) -> &[u8] {
        &self.admin_address
    }
    pub fn clear_admin_address(&mut self) {
        self.admin_address.clear();
    }

    // Param is passed by value, moved
    pub fn set_admin_address(&mut self, v: ::std::vec::Vec<u8>) {
        self.admin_address = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_admin_address(&mut self) -> &mut ::std::vec::Vec<u8> {
        &mut self.admin_address
    }

    // Take field
    pub fn take_admin_address(&mut self) -> ::std::vec::Vec<u8> {
        ::std::mem::replace(&mut self.admin_address, ::std::vec::Vec::new())
    }

    // uint32 version = 7;


    pub fn get_version(&self) -> u32 {
        self.version
    }
    pub fn clear_version(&mut self) {
        self.version = 0;
    }

    // Param is passed by value, moved
    pub fn set_version(&mut self, v: u32) {
        self.version = v;
    }
}

impl ::protobuf::Message for BlockTxHashes {
    fn is_initialized(&self) -> bool {
        for v in &self.account_quota_limit {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint64()?;
                    self.height = tmp;
                },
                2 => {
                    ::protobuf::rt::read_repeated_bytes_into(wire_type, is, &mut self.tx_hashes)?;
                },
                3 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint64()?;
                    self.block_quota_limit = tmp;
                },
                4 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.account_quota_limit)?;
                },
                5 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_bool()?;
                    self.check_quota = tmp;
                },
                6 => {
                    ::protobuf::rt::read_singular_proto3_bytes_into(wire_type, is, &mut self.admin_address)?;
                },
                7 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint32()?;
                    self.version = tmp;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if self.height != 0 {
            my_size += ::protobuf::rt::value_size(1, self.height, ::protobuf::wire_format::WireTypeVarint);
        }
        for value in &self.tx_hashes {
            my_size += ::protobuf::rt::bytes_size(2, &value);
        };
        if self.block_quota_limit != 0 {
            my_size += ::protobuf::rt::value_size(3, self.block_quota_limit, ::protobuf::wire_format::WireTypeVarint);
        }
        if let Some(ref v) = self.account_quota_limit.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        if self.check_quota != false {
            my_size += 2;
        }
        if !self.admin_address.is_empty() {
            my_size += ::protobuf::rt::bytes_size(6, &self.admin_address);
        }
        if self.version != 0 {
            my_size += ::protobuf::rt::value_size(7, self.version, ::protobuf::wire_format::WireTypeVarint);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if self.height != 0 {
            os.write_uint64(1, self.height)?;
        }
        for v in &self.tx_hashes {
            os.write_bytes(2, &v)?;
        };
        if self.block_quota_limit != 0 {
            os.write_uint64(3, self.block_quota_limit)?;
        }
        if let Some(ref v) = self.account_quota_limit.as_ref() {
            os.write_tag(4, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        if self.check_quota != false {
            os.write_bool(5, self.check_quota)?;
        }
        if !self.admin_address.is_empty() {
            os.write_bytes(6, &self.admin_address)?;
        }
        if self.version != 0 {
            os.write_uint32(7, self.version)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> BlockTxHashes {
        BlockTxHashes::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint64>(
                    "height",
                    |m: &BlockTxHashes| { &m.height },
                    |m: &mut BlockTxHashes| { &mut m.height },
                ));
                fields.push(::protobuf::reflect::accessor::make_repeated_field_accessor::<_, ::protobuf::types::ProtobufTypeBytes>(
                    "tx_hashes",
                    |m: &BlockTxHashes| { &m.tx_hashes },
                    |m: &mut BlockTxHashes| { &mut m.tx_hashes },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint64>(
                    "block_quota_limit",
                    |m: &BlockTxHashes| { &m.block_quota_limit },
                    |m: &mut BlockTxHashes| { &mut m.block_quota_limit },
                ));
                fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<super::blockchain::AccountGasLimit>>(
                    "account_quota_limit",
                    |m: &BlockTxHashes| { &m.account_quota_limit },
                    |m: &mut BlockTxHashes| { &mut m.account_quota_limit },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeBool>(
                    "check_quota",
                    |m: &BlockTxHashes| { &m.check_quota },
                    |m: &mut BlockTxHashes| { &mut m.check_quota },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeBytes>(
                    "admin_address",
                    |m: &BlockTxHashes| { &m.admin_address },
                    |m: &mut BlockTxHashes| { &mut m.admin_address },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint32>(
                    "version",
                    |m: &BlockTxHashes| { &m.version },
                    |m: &mut BlockTxHashes| { &mut m.version },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<BlockTxHashes>(
                    "BlockTxHashes",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static BlockTxHashes {
        static mut instance: ::protobuf::lazy::Lazy<BlockTxHashes> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const BlockTxHashes,
        };
        unsafe {
            instance.get(BlockTxHashes::new)
        }
    }
}

impl ::protobuf::Clear for BlockTxHashes {
    fn clear(&mut self) {
        self.height = 0;
        self.tx_hashes.clear();
        self.block_quota_limit = 0;
        self.account_quota_limit.clear();
        self.check_quota = false;
        self.admin_address.clear();
        self.version = 0;
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for BlockTxHashes {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for BlockTxHashes {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct BlockTxHashesReq {
    // message fields
    pub height: u64,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a BlockTxHashesReq {
    fn default() -> &'a BlockTxHashesReq {
        <BlockTxHashesReq as ::protobuf::Message>::default_instance()
    }
}

impl BlockTxHashesReq {
    pub fn new() -> BlockTxHashesReq {
        ::std::default::Default::default()
    }

    // uint64 height = 1;


    pub fn get_height(&self) -> u64 {
        self.height
    }
    pub fn clear_height(&mut self) {
        self.height = 0;
    }

    // Param is passed by value, moved
    pub fn set_height(&mut self, v: u64) {
        self.height = v;
    }
}

impl ::protobuf::Message for BlockTxHashesReq {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint64()?;
                    self.height = tmp;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if self.height != 0 {
            my_size += ::protobuf::rt::value_size(1, self.height, ::protobuf::wire_format::WireTypeVarint);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if self.height != 0 {
            os.write_uint64(1, self.height)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> BlockTxHashesReq {
        BlockTxHashesReq::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint64>(
                    "height",
                    |m: &BlockTxHashesReq| { &m.height },
                    |m: &mut BlockTxHashesReq| { &mut m.height },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<BlockTxHashesReq>(
                    "BlockTxHashesReq",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static BlockTxHashesReq {
        static mut instance: ::protobuf::lazy::Lazy<BlockTxHashesReq> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const BlockTxHashesReq,
        };
        unsafe {
            instance.get(BlockTxHashesReq::new)
        }
    }
}

impl ::protobuf::Clear for BlockTxHashesReq {
    fn clear(&mut self) {
        self.height = 0;
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for BlockTxHashesReq {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for BlockTxHashesReq {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct GetTxList {
    // message fields
    pub height: u64,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a GetTxList {
    fn default() -> &'a GetTxList {
        <GetTxList as ::protobuf::Message>::default_instance()
    }
}

impl GetTxList {
    pub fn new() -> GetTxList {
        ::std::default::Default::default()
    }

    // uint64 height = 1;


    pub fn get_height(&self) -> u64 {
        self.height
    }
    pub fn clear_height(&mut self) {
        self.height = 0;
    }

    // Param is passed by value, moved
    pub fn set_height(&mut self, v: u64) {
        self.height = v;
    }
}

impl ::protobuf::Message for GetTxList {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint64()?;
                    self.height = tmp;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if self.height != 0 {
            my_size += ::protobuf::rt::value_size(1, self.height, ::protobuf::wire_format::WireTypeVarint);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if self.height != 0 {
            os.write_uint64(1, self.height)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> GetTxList {
        GetTxList::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint64>(
                    "height",
                    |m: &GetTxList| { &m.height },
                    |m: &mut GetTxList| { &mut m.height },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<GetTxList>(
                    "GetTxList",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static GetTxList {
        static mut instance: ::protobuf::lazy::Lazy<GetTxList> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const GetTxList,
        };
        unsafe {
            instance.get(GetTxList::new)
        }
    }
}

impl ::protobuf::Clear for GetTxList {
    fn clear(&mut self) {
        self.height = 0;
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for GetTxList {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for GetTxList {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct Miscellaneous {
    // message fields
    pub chain_id: u32,
    pub chain_id_v1: ::std::vec::Vec<u8>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a Miscellaneous {
    fn default() -> &'a Miscellaneous {
        <Miscellaneous as ::protobuf::Message>::default_instance()
    }
}

impl Miscellaneous {
    pub fn new() -> Miscellaneous {
        ::std::default::Default::default()
    }

    // uint32 chain_id = 1;


    pub fn get_chain_id(&self) -> u32 {
        self.chain_id
    }
    pub fn clear_chain_id(&mut self) {
        self.chain_id = 0;
    }

    // Param is passed by value, moved
    pub fn set_chain_id(&mut self, v: u32) {
        self.chain_id = v;
    }

    // bytes chain_id_v1 = 2;


    pub fn get_chain_id_v1(&self) -> &[u8] {
        &self.chain_id_v1
    }
    pub fn clear_chain_id_v1(&mut self) {
        self.chain_id_v1.clear();
    }

    // Param is passed by value, moved
    pub fn set_chain_id_v1(&mut self, v: ::std::vec::Vec<u8>) {
        self.chain_id_v1 = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_chain_id_v1(&mut self) -> &mut ::std::vec::Vec<u8> {
        &mut self.chain_id_v1
    }

    // Take field
    pub fn take_chain_id_v1(&mut self) -> ::std::vec::Vec<u8> {
        ::std::mem::replace(&mut self.chain_id_v1, ::std::vec::Vec::new())
    }
}

impl ::protobuf::Message for Miscellaneous {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint32()?;
                    self.chain_id = tmp;
                },
                2 => {
                    ::protobuf::rt::read_singular_proto3_bytes_into(wire_type, is, &mut self.chain_id_v1)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if self.chain_id != 0 {
            my_size += ::protobuf::rt::value_size(1, self.chain_id, ::protobuf::wire_format::WireTypeVarint);
        }
        if !self.chain_id_v1.is_empty() {
            my_size += ::protobuf::rt::bytes_size(2, &self.chain_id_v1);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if self.chain_id != 0 {
            os.write_uint32(1, self.chain_id)?;
        }
        if !self.chain_id_v1.is_empty() {
            os.write_bytes(2, &self.chain_id_v1)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> Miscellaneous {
        Miscellaneous::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint32>(
                    "chain_id",
                    |m: &Miscellaneous| { &m.chain_id },
                    |m: &mut Miscellaneous| { &mut m.chain_id },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeBytes>(
                    "chain_id_v1",
                    |m: &Miscellaneous| { &m.chain_id_v1 },
                    |m: &mut Miscellaneous| { &mut m.chain_id_v1 },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<Miscellaneous>(
                    "Miscellaneous",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static Miscellaneous {
        static mut instance: ::protobuf::lazy::Lazy<Miscellaneous> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const Miscellaneous,
        };
        unsafe {
            instance.get(Miscellaneous::new)
        }
    }
}

impl ::protobuf::Clear for Miscellaneous {
    fn clear(&mut self) {
        self.chain_id = 0;
        self.chain_id_v1.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for Miscellaneous {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Miscellaneous {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct MiscellaneousReq {
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a MiscellaneousReq {
    fn default() -> &'a MiscellaneousReq {
        <MiscellaneousReq as ::protobuf::Message>::default_instance()
    }
}

impl MiscellaneousReq {
    pub fn new() -> MiscellaneousReq {
        ::std::default::Default::default()
    }
}

impl ::protobuf::Message for MiscellaneousReq {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> MiscellaneousReq {
        MiscellaneousReq::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let fields = ::std::vec::Vec::new();
                ::protobuf::reflect::MessageDescriptor::new::<MiscellaneousReq>(
                    "MiscellaneousReq",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static MiscellaneousReq {
        static mut instance: ::protobuf::lazy::Lazy<MiscellaneousReq> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const MiscellaneousReq,
        };
        unsafe {
            instance.get(MiscellaneousReq::new)
        }
    }
}

impl ::protobuf::Clear for MiscellaneousReq {
    fn clear(&mut self) {
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for MiscellaneousReq {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for MiscellaneousReq {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\nauth.proto\x1a\x10blockchain.proto\"\xba\x02\n\x0bVerifyTxReq\x12*\n\
    \x11valid_until_block\x18\x01\x20\x01(\x04R\x0fvalidUntilBlock\x12\x12\n\
    \x04hash\x18\x02\x20\x01(\x0cR\x04hash\x12\x1c\n\tsignature\x18\x03\x20\
    \x01(\x0cR\tsignature\x12\x1f\n\x06crypto\x18\x04\x20\x01(\x0e2\x07.Cryp\
    toR\x06crypto\x12\x17\n\x07tx_hash\x18\x05\x20\x01(\x0cR\x06txHash\x12\
    \x16\n\x06signer\x18\x06\x20\x01(\x0cR\x06signer\x12\x14\n\x05nonce\x18\
    \x07\x20\x01(\tR\x05nonce\x12\x19\n\x08chain_id\x18\x08\x20\x01(\rR\x07c\
    hainId\x12\x14\n\x05quota\x18\t\x20\x01(\x04R\x05quota\x12\x14\n\x05valu\
    e\x18\n\x20\x01(\x0cR\x05value\x12\x1e\n\x0bchain_id_v1\x18\x0b\x20\x01(\
    \x0cR\tchainIdV1\"c\n\x0eVerifyBlockReq\x12\x16\n\x06height\x18\x01\x20\
    \x01(\x04R\x06height\x12\x14\n\x05round\x18\x02\x20\x01(\x04R\x05round\
    \x12#\n\x05block\x18\x03\x20\x01(\x0b2\r.CompactBlockR\x05block\"q\n\x0f\
    VerifyBlockResp\x12\x16\n\x06height\x18\x01\x20\x01(\x04R\x06height\x12\
    \x14\n\x05round\x18\x02\x20\x01(\x04R\x05round\x12\x12\n\x04pass\x18\x03\
    \x20\x01(\x08R\x04pass\x12\x1c\n\x05block\x18\x04\x20\x01(\x0b2\x06.Bloc\
    kR\x05block\"\x92\x02\n\rBlockTxHashes\x12\x16\n\x06height\x18\x01\x20\
    \x01(\x04R\x06height\x12\x1b\n\ttx_hashes\x18\x02\x20\x03(\x0cR\x08txHas\
    hes\x12*\n\x11block_quota_limit\x18\x03\x20\x01(\x04R\x0fblockQuotaLimit\
    \x12@\n\x13account_quota_limit\x18\x04\x20\x01(\x0b2\x10.AccountGasLimit\
    R\x11accountQuotaLimit\x12\x1f\n\x0bcheck_quota\x18\x05\x20\x01(\x08R\nc\
    heckQuota\x12#\n\radmin_address\x18\x06\x20\x01(\x0cR\x0cadminAddress\
    \x12\x18\n\x07version\x18\x07\x20\x01(\rR\x07version\"*\n\x10BlockTxHash\
    esReq\x12\x16\n\x06height\x18\x01\x20\x01(\x04R\x06height\"#\n\tGetTxLis\
    t\x12\x16\n\x06height\x18\x01\x20\x01(\x04R\x06height\"J\n\rMiscellaneou\
    s\x12\x19\n\x08chain_id\x18\x01\x20\x01(\rR\x07chainId\x12\x1e\n\x0bchai\
    n_id_v1\x18\x02\x20\x01(\x0cR\tchainIdV1\"\x12\n\x10MiscellaneousReqJ\
    \xed\x11\n\x06\x12\x04\0\07\x01\n\x08\n\x01\x0c\x12\x03\0\0\x12\n\t\n\
    \x02\x03\0\x12\x03\x02\x07\x19\n\n\n\x02\x04\0\x12\x04\x04\0\x10\x01\n\n\
    \n\x03\x04\0\x01\x12\x03\x04\x08\x13\n\x0b\n\x04\x04\0\x02\0\x12\x03\x05\
    \x04!\n\r\n\x05\x04\0\x02\0\x04\x12\x04\x05\x04\x04\x15\n\x0c\n\x05\x04\
    \0\x02\0\x05\x12\x03\x05\x04\n\n\x0c\n\x05\x04\0\x02\0\x01\x12\x03\x05\
    \x0b\x1c\n\x0c\n\x05\x04\0\x02\0\x03\x12\x03\x05\x1f\x20\n\x0b\n\x04\x04\
    \0\x02\x01\x12\x03\x06\x04\x13\n\r\n\x05\x04\0\x02\x01\x04\x12\x04\x06\
    \x04\x05!\n\x0c\n\x05\x04\0\x02\x01\x05\x12\x03\x06\x04\t\n\x0c\n\x05\
    \x04\0\x02\x01\x01\x12\x03\x06\n\x0e\n\x0c\n\x05\x04\0\x02\x01\x03\x12\
    \x03\x06\x11\x12\n\x0b\n\x04\x04\0\x02\x02\x12\x03\x07\x04\x18\n\r\n\x05\
    \x04\0\x02\x02\x04\x12\x04\x07\x04\x06\x13\n\x0c\n\x05\x04\0\x02\x02\x05\
    \x12\x03\x07\x04\t\n\x0c\n\x05\x04\0\x02\x02\x01\x12\x03\x07\n\x13\n\x0c\
    \n\x05\x04\0\x02\x02\x03\x12\x03\x07\x16\x17\n\x0b\n\x04\x04\0\x02\x03\
    \x12\x03\x08\x04\x16\n\r\n\x05\x04\0\x02\x03\x04\x12\x04\x08\x04\x07\x18\
    \n\x0c\n\x05\x04\0\x02\x03\x06\x12\x03\x08\x04\n\n\x0c\n\x05\x04\0\x02\
    \x03\x01\x12\x03\x08\x0b\x11\n\x0c\n\x05\x04\0\x02\x03\x03\x12\x03\x08\
    \x14\x15\n\x0b\n\x04\x04\0\x02\x04\x12\x03\t\x04\x16\n\r\n\x05\x04\0\x02\
    \x04\x04\x12\x04\t\x04\x08\x16\n\x0c\n\x05\x04\0\x02\x04\x05\x12\x03\t\
    \x04\t\n\x0c\n\x05\x04\0\x02\x04\x01\x12\x03\t\n\x11\n\x0c\n\x05\x04\0\
    \x02\x04\x03\x12\x03\t\x14\x15\n.\n\x04\x04\0\x02\x05\x12\x03\n\x04\x15\
    \"!\x20public\x20key\x20only\x20set\x20in\x20BlockReq\n\n\r\n\x05\x04\0\
    \x02\x05\x04\x12\x04\n\x04\t\x16\n\x0c\n\x05\x04\0\x02\x05\x05\x12\x03\n\
    \x04\t\n\x0c\n\x05\x04\0\x02\x05\x01\x12\x03\n\n\x10\n\x0c\n\x05\x04\0\
    \x02\x05\x03\x12\x03\n\x13\x14\n\x0b\n\x04\x04\0\x02\x06\x12\x03\x0b\x04\
    \x15\n\r\n\x05\x04\0\x02\x06\x04\x12\x04\x0b\x04\n\x15\n\x0c\n\x05\x04\0\
    \x02\x06\x05\x12\x03\x0b\x04\n\n\x0c\n\x05\x04\0\x02\x06\x01\x12\x03\x0b\
    \x0b\x10\n\x0c\n\x05\x04\0\x02\x06\x03\x12\x03\x0b\x13\x14\n\x0b\n\x04\
    \x04\0\x02\x07\x12\x03\x0c\x04\x18\n\r\n\x05\x04\0\x02\x07\x04\x12\x04\
    \x0c\x04\x0b\x15\n\x0c\n\x05\x04\0\x02\x07\x05\x12\x03\x0c\x04\n\n\x0c\n\
    \x05\x04\0\x02\x07\x01\x12\x03\x0c\x0b\x13\n\x0c\n\x05\x04\0\x02\x07\x03\
    \x12\x03\x0c\x16\x17\n\x0b\n\x04\x04\0\x02\x08\x12\x03\r\x04\x15\n\r\n\
    \x05\x04\0\x02\x08\x04\x12\x04\r\x04\x0c\x18\n\x0c\n\x05\x04\0\x02\x08\
    \x05\x12\x03\r\x04\n\n\x0c\n\x05\x04\0\x02\x08\x01\x12\x03\r\x0b\x10\n\
    \x0c\n\x05\x04\0\x02\x08\x03\x12\x03\r\x13\x14\n\x0b\n\x04\x04\0\x02\t\
    \x12\x03\x0e\x04\x15\n\r\n\x05\x04\0\x02\t\x04\x12\x04\x0e\x04\r\x15\n\
    \x0c\n\x05\x04\0\x02\t\x05\x12\x03\x0e\x04\t\n\x0c\n\x05\x04\0\x02\t\x01\
    \x12\x03\x0e\n\x0f\n\x0c\n\x05\x04\0\x02\t\x03\x12\x03\x0e\x12\x14\n\x0b\
    \n\x04\x04\0\x02\n\x12\x03\x0f\x04\x1b\n\r\n\x05\x04\0\x02\n\x04\x12\x04\
    \x0f\x04\x0e\x15\n\x0c\n\x05\x04\0\x02\n\x05\x12\x03\x0f\x04\t\n\x0c\n\
    \x05\x04\0\x02\n\x01\x12\x03\x0f\n\x15\n\x0c\n\x05\x04\0\x02\n\x03\x12\
    \x03\x0f\x18\x1a\n\n\n\x02\x04\x01\x12\x04\x12\0\x16\x01\n\n\n\x03\x04\
    \x01\x01\x12\x03\x12\x08\x16\n\x0b\n\x04\x04\x01\x02\0\x12\x03\x13\x04\
    \x16\n\r\n\x05\x04\x01\x02\0\x04\x12\x04\x13\x04\x12\x18\n\x0c\n\x05\x04\
    \x01\x02\0\x05\x12\x03\x13\x04\n\n\x0c\n\x05\x04\x01\x02\0\x01\x12\x03\
    \x13\x0b\x11\n\x0c\n\x05\x04\x01\x02\0\x03\x12\x03\x13\x14\x15\n\x0b\n\
    \x04\x04\x01\x02\x01\x12\x03\x14\x04\x15\n\r\n\x05\x04\x01\x02\x01\x04\
    \x12\x04\x14\x04\x13\x16\n\x0c\n\x05\x04\x01\x02\x01\x05\x12\x03\x14\x04\
    \n\n\x0c\n\x05\x04\x01\x02\x01\x01\x12\x03\x14\x0b\x10\n\x0c\n\x05\x04\
    \x01\x02\x01\x03\x12\x03\x14\x13\x14\n\x0b\n\x04\x04\x01\x02\x02\x12\x03\
    \x15\x04\x1b\n\r\n\x05\x04\x01\x02\x02\x04\x12\x04\x15\x04\x14\x15\n\x0c\
    \n\x05\x04\x01\x02\x02\x06\x12\x03\x15\x04\x10\n\x0c\n\x05\x04\x01\x02\
    \x02\x01\x12\x03\x15\x11\x16\n\x0c\n\x05\x04\x01\x02\x02\x03\x12\x03\x15\
    \x19\x1a\n\n\n\x02\x04\x02\x12\x04\x18\0\x1d\x01\n\n\n\x03\x04\x02\x01\
    \x12\x03\x18\x08\x17\n\x0b\n\x04\x04\x02\x02\0\x12\x03\x19\x04\x16\n\r\n\
    \x05\x04\x02\x02\0\x04\x12\x04\x19\x04\x18\x19\n\x0c\n\x05\x04\x02\x02\0\
    \x05\x12\x03\x19\x04\n\n\x0c\n\x05\x04\x02\x02\0\x01\x12\x03\x19\x0b\x11\
    \n\x0c\n\x05\x04\x02\x02\0\x03\x12\x03\x19\x14\x15\n\x0b\n\x04\x04\x02\
    \x02\x01\x12\x03\x1a\x04\x15\n\r\n\x05\x04\x02\x02\x01\x04\x12\x04\x1a\
    \x04\x19\x16\n\x0c\n\x05\x04\x02\x02\x01\x05\x12\x03\x1a\x04\n\n\x0c\n\
    \x05\x04\x02\x02\x01\x01\x12\x03\x1a\x0b\x10\n\x0c\n\x05\x04\x02\x02\x01\
    \x03\x12\x03\x1a\x13\x14\n\x0b\n\x04\x04\x02\x02\x02\x12\x03\x1b\x04\x12\
    \n\r\n\x05\x04\x02\x02\x02\x04\x12\x04\x1b\x04\x1a\x15\n\x0c\n\x05\x04\
    \x02\x02\x02\x05\x12\x03\x1b\x04\x08\n\x0c\n\x05\x04\x02\x02\x02\x01\x12\
    \x03\x1b\t\r\n\x0c\n\x05\x04\x02\x02\x02\x03\x12\x03\x1b\x10\x11\n\x0b\n\
    \x04\x04\x02\x02\x03\x12\x03\x1c\x04\x14\n\r\n\x05\x04\x02\x02\x03\x04\
    \x12\x04\x1c\x04\x1b\x12\n\x0c\n\x05\x04\x02\x02\x03\x06\x12\x03\x1c\x04\
    \t\n\x0c\n\x05\x04\x02\x02\x03\x01\x12\x03\x1c\n\x0f\n\x0c\n\x05\x04\x02\
    \x02\x03\x03\x12\x03\x1c\x12\x13\n\n\n\x02\x04\x03\x12\x04\x1f\0'\x01\n\
    \n\n\x03\x04\x03\x01\x12\x03\x1f\x08\x15\n\x0b\n\x04\x04\x03\x02\0\x12\
    \x03\x20\x04\x16\n\r\n\x05\x04\x03\x02\0\x04\x12\x04\x20\x04\x1f\x17\n\
    \x0c\n\x05\x04\x03\x02\0\x05\x12\x03\x20\x04\n\n\x0c\n\x05\x04\x03\x02\0\
    \x01\x12\x03\x20\x0b\x11\n\x0c\n\x05\x04\x03\x02\0\x03\x12\x03\x20\x14\
    \x15\n\x0b\n\x04\x04\x03\x02\x01\x12\x03!\x04!\n\x0c\n\x05\x04\x03\x02\
    \x01\x04\x12\x03!\x04\x0c\n\x0c\n\x05\x04\x03\x02\x01\x05\x12\x03!\r\x12\
    \n\x0c\n\x05\x04\x03\x02\x01\x01\x12\x03!\x13\x1c\n\x0c\n\x05\x04\x03\
    \x02\x01\x03\x12\x03!\x1f\x20\n\x0b\n\x04\x04\x03\x02\x02\x12\x03\"\x04!\
    \n\r\n\x05\x04\x03\x02\x02\x04\x12\x04\"\x04!!\n\x0c\n\x05\x04\x03\x02\
    \x02\x05\x12\x03\"\x04\n\n\x0c\n\x05\x04\x03\x02\x02\x01\x12\x03\"\x0b\
    \x1c\n\x0c\n\x05\x04\x03\x02\x02\x03\x12\x03\"\x1f\x20\n\x0b\n\x04\x04\
    \x03\x02\x03\x12\x03#\x04,\n\r\n\x05\x04\x03\x02\x03\x04\x12\x04#\x04\"!\
    \n\x0c\n\x05\x04\x03\x02\x03\x06\x12\x03#\x04\x13\n\x0c\n\x05\x04\x03\
    \x02\x03\x01\x12\x03#\x14'\n\x0c\n\x05\x04\x03\x02\x03\x03\x12\x03#*+\n\
    \x0b\n\x04\x04\x03\x02\x04\x12\x03$\x04\x19\n\r\n\x05\x04\x03\x02\x04\
    \x04\x12\x04$\x04#,\n\x0c\n\x05\x04\x03\x02\x04\x05\x12\x03$\x04\x08\n\
    \x0c\n\x05\x04\x03\x02\x04\x01\x12\x03$\t\x14\n\x0c\n\x05\x04\x03\x02\
    \x04\x03\x12\x03$\x17\x18\n\x0b\n\x04\x04\x03\x02\x05\x12\x03%\x04\x1c\n\
    \r\n\x05\x04\x03\x02\x05\x04\x12\x04%\x04$\x19\n\x0c\n\x05\x04\x03\x02\
    \x05\x05\x12\x03%\x04\t\n\x0c\n\x05\x04\x03\x02\x05\x01\x12\x03%\n\x17\n\
    \x0c\n\x05\x04\x03\x02\x05\x03\x12\x03%\x1a\x1b\n\x0b\n\x04\x04\x03\x02\
    \x06\x12\x03&\x04\x17\n\r\n\x05\x04\x03\x02\x06\x04\x12\x04&\x04%\x1c\n\
    \x0c\n\x05\x04\x03\x02\x06\x05\x12\x03&\x04\n\n\x0c\n\x05\x04\x03\x02\
    \x06\x01\x12\x03&\x0b\x12\n\x0c\n\x05\x04\x03\x02\x06\x03\x12\x03&\x15\
    \x16\n\n\n\x02\x04\x04\x12\x04)\0+\x01\n\n\n\x03\x04\x04\x01\x12\x03)\
    \x08\x18\n\x0b\n\x04\x04\x04\x02\0\x12\x03*\x04\x16\n\r\n\x05\x04\x04\
    \x02\0\x04\x12\x04*\x04)\x1a\n\x0c\n\x05\x04\x04\x02\0\x05\x12\x03*\x04\
    \n\n\x0c\n\x05\x04\x04\x02\0\x01\x12\x03*\x0b\x11\n\x0c\n\x05\x04\x04\
    \x02\0\x03\x12\x03*\x14\x15\n\n\n\x02\x04\x05\x12\x04-\0/\x01\n\n\n\x03\
    \x04\x05\x01\x12\x03-\x08\x11\n\x0b\n\x04\x04\x05\x02\0\x12\x03.\x04\x16\
    \n\r\n\x05\x04\x05\x02\0\x04\x12\x04.\x04-\x13\n\x0c\n\x05\x04\x05\x02\0\
    \x05\x12\x03.\x04\n\n\x0c\n\x05\x04\x05\x02\0\x01\x12\x03.\x0b\x11\n\x0c\
    \n\x05\x04\x05\x02\0\x03\x12\x03.\x14\x15\n\n\n\x02\x04\x06\x12\x041\04\
    \x01\n\n\n\x03\x04\x06\x01\x12\x031\x08\x15\n\x0b\n\x04\x04\x06\x02\0\
    \x12\x032\x04\x18\n\r\n\x05\x04\x06\x02\0\x04\x12\x042\x041\x17\n\x0c\n\
    \x05\x04\x06\x02\0\x05\x12\x032\x04\n\n\x0c\n\x05\x04\x06\x02\0\x01\x12\
    \x032\x0b\x13\n\x0c\n\x05\x04\x06\x02\0\x03\x12\x032\x16\x17\n\x0b\n\x04\
    \x04\x06\x02\x01\x12\x033\x04\x1a\n\r\n\x05\x04\x06\x02\x01\x04\x12\x043\
    \x042\x18\n\x0c\n\x05\x04\x06\x02\x01\x05\x12\x033\x04\t\n\x0c\n\x05\x04\
    \x06\x02\x01\x01\x12\x033\n\x15\n\x0c\n\x05\x04\x06\x02\x01\x03\x12\x033\
    \x18\x19\n\n\n\x02\x04\x07\x12\x046\07\x01\n\n\n\x03\x04\x07\x01\x12\x03\
    6\x08\x18b\x06proto3\
";

static mut file_descriptor_proto_lazy: ::protobuf::lazy::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::lazy::Lazy {
    lock: ::protobuf::lazy::ONCE_INIT,
    ptr: 0 as *const ::protobuf::descriptor::FileDescriptorProto,
};

fn parse_descriptor_proto() -> ::protobuf::descriptor::FileDescriptorProto {
    ::protobuf::parse_from_bytes(file_descriptor_proto_data).unwrap()
}

pub fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    unsafe {
        file_descriptor_proto_lazy.get(|| {
            parse_descriptor_proto()
        })
    }
}
