// CITA
// Copyright 2016-2018 Cryptape Technologies LLC.

// This program is free software: you can redistribute it
// and/or modify it under the terms of the GNU General Public
// License as published by the Free Software Foundation,
// either version 3 of the License, or (at your option) any
// later version.

// This program is distributed in the hope that it will be
// useful, but WITHOUT ANY WARRANTY; without even the implied
// warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
// PURPOSE. See the GNU General Public License for more details.

// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

// This file is generated by rust-protobuf 2.0.4. Do not edit
// @generated

// https://github.com/Manishearth/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy)]

#![cfg_attr(rustfmt, rustfmt_skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unsafe_code)]
#![allow(unused_imports)]
#![allow(unused_results)]

use protobuf::Message as Message_imported_for_functions;
use protobuf::ProtobufEnum as ProtobufEnum_imported_for_functions;

#[derive(PartialEq,Clone,Default)]
pub struct VerifyTxReq {
    // message fields
    pub valid_until_block: u64,
    pub hash: ::std::vec::Vec<u8>,
    pub signature: ::std::vec::Vec<u8>,
    pub crypto: super::blockchain::Crypto,
    pub tx_hash: ::std::vec::Vec<u8>,
    pub signer: ::std::vec::Vec<u8>,
    pub nonce: ::std::string::String,
    pub chain_id: u32,
    pub quota: u64,
    pub value: ::std::vec::Vec<u8>,
    pub chain_id_v1: ::std::vec::Vec<u8>,
    // special fields
    unknown_fields: ::protobuf::UnknownFields,
    cached_size: ::protobuf::CachedSize,
}

impl VerifyTxReq {
    pub fn new() -> VerifyTxReq {
        ::std::default::Default::default()
    }

    // uint64 valid_until_block = 1;

    pub fn clear_valid_until_block(&mut self) {
        self.valid_until_block = 0;
    }

    // Param is passed by value, moved
    pub fn set_valid_until_block(&mut self, v: u64) {
        self.valid_until_block = v;
    }

    pub fn get_valid_until_block(&self) -> u64 {
        self.valid_until_block
    }

    // bytes hash = 2;

    pub fn clear_hash(&mut self) {
        self.hash.clear();
    }

    // Param is passed by value, moved
    pub fn set_hash(&mut self, v: ::std::vec::Vec<u8>) {
        self.hash = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_hash(&mut self) -> &mut ::std::vec::Vec<u8> {
        &mut self.hash
    }

    // Take field
    pub fn take_hash(&mut self) -> ::std::vec::Vec<u8> {
        ::std::mem::replace(&mut self.hash, ::std::vec::Vec::new())
    }

    pub fn get_hash(&self) -> &[u8] {
        &self.hash
    }

    // bytes signature = 3;

    pub fn clear_signature(&mut self) {
        self.signature.clear();
    }

    // Param is passed by value, moved
    pub fn set_signature(&mut self, v: ::std::vec::Vec<u8>) {
        self.signature = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_signature(&mut self) -> &mut ::std::vec::Vec<u8> {
        &mut self.signature
    }

    // Take field
    pub fn take_signature(&mut self) -> ::std::vec::Vec<u8> {
        ::std::mem::replace(&mut self.signature, ::std::vec::Vec::new())
    }

    pub fn get_signature(&self) -> &[u8] {
        &self.signature
    }

    // .Crypto crypto = 4;

    pub fn clear_crypto(&mut self) {
        self.crypto = super::blockchain::Crypto::SECP;
    }

    // Param is passed by value, moved
    pub fn set_crypto(&mut self, v: super::blockchain::Crypto) {
        self.crypto = v;
    }

    pub fn get_crypto(&self) -> super::blockchain::Crypto {
        self.crypto
    }

    // bytes tx_hash = 5;

    pub fn clear_tx_hash(&mut self) {
        self.tx_hash.clear();
    }

    // Param is passed by value, moved
    pub fn set_tx_hash(&mut self, v: ::std::vec::Vec<u8>) {
        self.tx_hash = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_tx_hash(&mut self) -> &mut ::std::vec::Vec<u8> {
        &mut self.tx_hash
    }

    // Take field
    pub fn take_tx_hash(&mut self) -> ::std::vec::Vec<u8> {
        ::std::mem::replace(&mut self.tx_hash, ::std::vec::Vec::new())
    }

    pub fn get_tx_hash(&self) -> &[u8] {
        &self.tx_hash
    }

    // bytes signer = 6;

    pub fn clear_signer(&mut self) {
        self.signer.clear();
    }

    // Param is passed by value, moved
    pub fn set_signer(&mut self, v: ::std::vec::Vec<u8>) {
        self.signer = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_signer(&mut self) -> &mut ::std::vec::Vec<u8> {
        &mut self.signer
    }

    // Take field
    pub fn take_signer(&mut self) -> ::std::vec::Vec<u8> {
        ::std::mem::replace(&mut self.signer, ::std::vec::Vec::new())
    }

    pub fn get_signer(&self) -> &[u8] {
        &self.signer
    }

    // string nonce = 7;

    pub fn clear_nonce(&mut self) {
        self.nonce.clear();
    }

    // Param is passed by value, moved
    pub fn set_nonce(&mut self, v: ::std::string::String) {
        self.nonce = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_nonce(&mut self) -> &mut ::std::string::String {
        &mut self.nonce
    }

    // Take field
    pub fn take_nonce(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.nonce, ::std::string::String::new())
    }

    pub fn get_nonce(&self) -> &str {
        &self.nonce
    }

    // uint32 chain_id = 8;

    pub fn clear_chain_id(&mut self) {
        self.chain_id = 0;
    }

    // Param is passed by value, moved
    pub fn set_chain_id(&mut self, v: u32) {
        self.chain_id = v;
    }

    pub fn get_chain_id(&self) -> u32 {
        self.chain_id
    }

    // uint64 quota = 9;

    pub fn clear_quota(&mut self) {
        self.quota = 0;
    }

    // Param is passed by value, moved
    pub fn set_quota(&mut self, v: u64) {
        self.quota = v;
    }

    pub fn get_quota(&self) -> u64 {
        self.quota
    }

    // bytes value = 10;

    pub fn clear_value(&mut self) {
        self.value.clear();
    }

    // Param is passed by value, moved
    pub fn set_value(&mut self, v: ::std::vec::Vec<u8>) {
        self.value = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_value(&mut self) -> &mut ::std::vec::Vec<u8> {
        &mut self.value
    }

    // Take field
    pub fn take_value(&mut self) -> ::std::vec::Vec<u8> {
        ::std::mem::replace(&mut self.value, ::std::vec::Vec::new())
    }

    pub fn get_value(&self) -> &[u8] {
        &self.value
    }

    // bytes chain_id_v1 = 11;

    pub fn clear_chain_id_v1(&mut self) {
        self.chain_id_v1.clear();
    }

    // Param is passed by value, moved
    pub fn set_chain_id_v1(&mut self, v: ::std::vec::Vec<u8>) {
        self.chain_id_v1 = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_chain_id_v1(&mut self) -> &mut ::std::vec::Vec<u8> {
        &mut self.chain_id_v1
    }

    // Take field
    pub fn take_chain_id_v1(&mut self) -> ::std::vec::Vec<u8> {
        ::std::mem::replace(&mut self.chain_id_v1, ::std::vec::Vec::new())
    }

    pub fn get_chain_id_v1(&self) -> &[u8] {
        &self.chain_id_v1
    }
}

impl ::protobuf::Message for VerifyTxReq {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint64()?;
                    self.valid_until_block = tmp;
                },
                2 => {
                    ::protobuf::rt::read_singular_proto3_bytes_into(wire_type, is, &mut self.hash)?;
                },
                3 => {
                    ::protobuf::rt::read_singular_proto3_bytes_into(wire_type, is, &mut self.signature)?;
                },
                4 => {
                    ::protobuf::rt::read_proto3_enum_with_unknown_fields_into(wire_type, is, &mut self.crypto, 4, &mut self.unknown_fields)?
                },
                5 => {
                    ::protobuf::rt::read_singular_proto3_bytes_into(wire_type, is, &mut self.tx_hash)?;
                },
                6 => {
                    ::protobuf::rt::read_singular_proto3_bytes_into(wire_type, is, &mut self.signer)?;
                },
                7 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.nonce)?;
                },
                8 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint32()?;
                    self.chain_id = tmp;
                },
                9 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint64()?;
                    self.quota = tmp;
                },
                10 => {
                    ::protobuf::rt::read_singular_proto3_bytes_into(wire_type, is, &mut self.value)?;
                },
                11 => {
                    ::protobuf::rt::read_singular_proto3_bytes_into(wire_type, is, &mut self.chain_id_v1)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if self.valid_until_block != 0 {
            my_size += ::protobuf::rt::value_size(1, self.valid_until_block, ::protobuf::wire_format::WireTypeVarint);
        }
        if !self.hash.is_empty() {
            my_size += ::protobuf::rt::bytes_size(2, &self.hash);
        }
        if !self.signature.is_empty() {
            my_size += ::protobuf::rt::bytes_size(3, &self.signature);
        }
        if self.crypto != super::blockchain::Crypto::SECP {
            my_size += ::protobuf::rt::enum_size(4, self.crypto);
        }
        if !self.tx_hash.is_empty() {
            my_size += ::protobuf::rt::bytes_size(5, &self.tx_hash);
        }
        if !self.signer.is_empty() {
            my_size += ::protobuf::rt::bytes_size(6, &self.signer);
        }
        if !self.nonce.is_empty() {
            my_size += ::protobuf::rt::string_size(7, &self.nonce);
        }
        if self.chain_id != 0 {
            my_size += ::protobuf::rt::value_size(8, self.chain_id, ::protobuf::wire_format::WireTypeVarint);
        }
        if self.quota != 0 {
            my_size += ::protobuf::rt::value_size(9, self.quota, ::protobuf::wire_format::WireTypeVarint);
        }
        if !self.value.is_empty() {
            my_size += ::protobuf::rt::bytes_size(10, &self.value);
        }
        if !self.chain_id_v1.is_empty() {
            my_size += ::protobuf::rt::bytes_size(11, &self.chain_id_v1);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream) -> ::protobuf::ProtobufResult<()> {
        if self.valid_until_block != 0 {
            os.write_uint64(1, self.valid_until_block)?;
        }
        if !self.hash.is_empty() {
            os.write_bytes(2, &self.hash)?;
        }
        if !self.signature.is_empty() {
            os.write_bytes(3, &self.signature)?;
        }
        if self.crypto != super::blockchain::Crypto::SECP {
            os.write_enum(4, self.crypto.value())?;
        }
        if !self.tx_hash.is_empty() {
            os.write_bytes(5, &self.tx_hash)?;
        }
        if !self.signer.is_empty() {
            os.write_bytes(6, &self.signer)?;
        }
        if !self.nonce.is_empty() {
            os.write_string(7, &self.nonce)?;
        }
        if self.chain_id != 0 {
            os.write_uint32(8, self.chain_id)?;
        }
        if self.quota != 0 {
            os.write_uint64(9, self.quota)?;
        }
        if !self.value.is_empty() {
            os.write_bytes(10, &self.value)?;
        }
        if !self.chain_id_v1.is_empty() {
            os.write_bytes(11, &self.chain_id_v1)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &::std::any::Any {
        self as &::std::any::Any
    }
    fn as_any_mut(&mut self) -> &mut ::std::any::Any {
        self as &mut ::std::any::Any
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<::std::any::Any> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> VerifyTxReq {
        VerifyTxReq::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint64>(
                    "valid_until_block",
                    |m: &VerifyTxReq| { &m.valid_until_block },
                    |m: &mut VerifyTxReq| { &mut m.valid_until_block },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeBytes>(
                    "hash",
                    |m: &VerifyTxReq| { &m.hash },
                    |m: &mut VerifyTxReq| { &mut m.hash },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeBytes>(
                    "signature",
                    |m: &VerifyTxReq| { &m.signature },
                    |m: &mut VerifyTxReq| { &mut m.signature },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeEnum<super::blockchain::Crypto>>(
                    "crypto",
                    |m: &VerifyTxReq| { &m.crypto },
                    |m: &mut VerifyTxReq| { &mut m.crypto },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeBytes>(
                    "tx_hash",
                    |m: &VerifyTxReq| { &m.tx_hash },
                    |m: &mut VerifyTxReq| { &mut m.tx_hash },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeBytes>(
                    "signer",
                    |m: &VerifyTxReq| { &m.signer },
                    |m: &mut VerifyTxReq| { &mut m.signer },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "nonce",
                    |m: &VerifyTxReq| { &m.nonce },
                    |m: &mut VerifyTxReq| { &mut m.nonce },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint32>(
                    "chain_id",
                    |m: &VerifyTxReq| { &m.chain_id },
                    |m: &mut VerifyTxReq| { &mut m.chain_id },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint64>(
                    "quota",
                    |m: &VerifyTxReq| { &m.quota },
                    |m: &mut VerifyTxReq| { &mut m.quota },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeBytes>(
                    "value",
                    |m: &VerifyTxReq| { &m.value },
                    |m: &mut VerifyTxReq| { &mut m.value },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeBytes>(
                    "chain_id_v1",
                    |m: &VerifyTxReq| { &m.chain_id_v1 },
                    |m: &mut VerifyTxReq| { &mut m.chain_id_v1 },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<VerifyTxReq>(
                    "VerifyTxReq",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static VerifyTxReq {
        static mut instance: ::protobuf::lazy::Lazy<VerifyTxReq> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const VerifyTxReq,
        };
        unsafe {
            instance.get(VerifyTxReq::new)
        }
    }
}

impl ::protobuf::Clear for VerifyTxReq {
    fn clear(&mut self) {
        self.clear_valid_until_block();
        self.clear_hash();
        self.clear_signature();
        self.clear_crypto();
        self.clear_tx_hash();
        self.clear_signer();
        self.clear_nonce();
        self.clear_chain_id();
        self.clear_quota();
        self.clear_value();
        self.clear_chain_id_v1();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for VerifyTxReq {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for VerifyTxReq {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct VerifyBlockReq {
    // message fields
    pub id: u64,
    pub reqs: ::protobuf::RepeatedField<VerifyTxReq>,
    // special fields
    unknown_fields: ::protobuf::UnknownFields,
    cached_size: ::protobuf::CachedSize,
}

impl VerifyBlockReq {
    pub fn new() -> VerifyBlockReq {
        ::std::default::Default::default()
    }

    // uint64 id = 1;

    pub fn clear_id(&mut self) {
        self.id = 0;
    }

    // Param is passed by value, moved
    pub fn set_id(&mut self, v: u64) {
        self.id = v;
    }

    pub fn get_id(&self) -> u64 {
        self.id
    }

    // repeated .VerifyTxReq reqs = 2;

    pub fn clear_reqs(&mut self) {
        self.reqs.clear();
    }

    // Param is passed by value, moved
    pub fn set_reqs(&mut self, v: ::protobuf::RepeatedField<VerifyTxReq>) {
        self.reqs = v;
    }

    // Mutable pointer to the field.
    pub fn mut_reqs(&mut self) -> &mut ::protobuf::RepeatedField<VerifyTxReq> {
        &mut self.reqs
    }

    // Take field
    pub fn take_reqs(&mut self) -> ::protobuf::RepeatedField<VerifyTxReq> {
        ::std::mem::replace(&mut self.reqs, ::protobuf::RepeatedField::new())
    }

    pub fn get_reqs(&self) -> &[VerifyTxReq] {
        &self.reqs
    }
}

impl ::protobuf::Message for VerifyBlockReq {
    fn is_initialized(&self) -> bool {
        for v in &self.reqs {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint64()?;
                    self.id = tmp;
                },
                2 => {
                    ::protobuf::rt::read_repeated_message_into(wire_type, is, &mut self.reqs)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if self.id != 0 {
            my_size += ::protobuf::rt::value_size(1, self.id, ::protobuf::wire_format::WireTypeVarint);
        }
        for value in &self.reqs {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream) -> ::protobuf::ProtobufResult<()> {
        if self.id != 0 {
            os.write_uint64(1, self.id)?;
        }
        for v in &self.reqs {
            os.write_tag(2, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        };
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &::std::any::Any {
        self as &::std::any::Any
    }
    fn as_any_mut(&mut self) -> &mut ::std::any::Any {
        self as &mut ::std::any::Any
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<::std::any::Any> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> VerifyBlockReq {
        VerifyBlockReq::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint64>(
                    "id",
                    |m: &VerifyBlockReq| { &m.id },
                    |m: &mut VerifyBlockReq| { &mut m.id },
                ));
                fields.push(::protobuf::reflect::accessor::make_repeated_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<VerifyTxReq>>(
                    "reqs",
                    |m: &VerifyBlockReq| { &m.reqs },
                    |m: &mut VerifyBlockReq| { &mut m.reqs },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<VerifyBlockReq>(
                    "VerifyBlockReq",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static VerifyBlockReq {
        static mut instance: ::protobuf::lazy::Lazy<VerifyBlockReq> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const VerifyBlockReq,
        };
        unsafe {
            instance.get(VerifyBlockReq::new)
        }
    }
}

impl ::protobuf::Clear for VerifyBlockReq {
    fn clear(&mut self) {
        self.clear_id();
        self.clear_reqs();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for VerifyBlockReq {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for VerifyBlockReq {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct VerifyBlockResp {
    // message fields
    pub id: u64,
    pub ret: Ret,
    // special fields
    unknown_fields: ::protobuf::UnknownFields,
    cached_size: ::protobuf::CachedSize,
}

impl VerifyBlockResp {
    pub fn new() -> VerifyBlockResp {
        ::std::default::Default::default()
    }

    // uint64 id = 1;

    pub fn clear_id(&mut self) {
        self.id = 0;
    }

    // Param is passed by value, moved
    pub fn set_id(&mut self, v: u64) {
        self.id = v;
    }

    pub fn get_id(&self) -> u64 {
        self.id
    }

    // .Ret ret = 2;

    pub fn clear_ret(&mut self) {
        self.ret = Ret::OK;
    }

    // Param is passed by value, moved
    pub fn set_ret(&mut self, v: Ret) {
        self.ret = v;
    }

    pub fn get_ret(&self) -> Ret {
        self.ret
    }
}

impl ::protobuf::Message for VerifyBlockResp {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint64()?;
                    self.id = tmp;
                },
                2 => {
                    ::protobuf::rt::read_proto3_enum_with_unknown_fields_into(wire_type, is, &mut self.ret, 2, &mut self.unknown_fields)?
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if self.id != 0 {
            my_size += ::protobuf::rt::value_size(1, self.id, ::protobuf::wire_format::WireTypeVarint);
        }
        if self.ret != Ret::OK {
            my_size += ::protobuf::rt::enum_size(2, self.ret);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream) -> ::protobuf::ProtobufResult<()> {
        if self.id != 0 {
            os.write_uint64(1, self.id)?;
        }
        if self.ret != Ret::OK {
            os.write_enum(2, self.ret.value())?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &::std::any::Any {
        self as &::std::any::Any
    }
    fn as_any_mut(&mut self) -> &mut ::std::any::Any {
        self as &mut ::std::any::Any
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<::std::any::Any> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> VerifyBlockResp {
        VerifyBlockResp::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint64>(
                    "id",
                    |m: &VerifyBlockResp| { &m.id },
                    |m: &mut VerifyBlockResp| { &mut m.id },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeEnum<Ret>>(
                    "ret",
                    |m: &VerifyBlockResp| { &m.ret },
                    |m: &mut VerifyBlockResp| { &mut m.ret },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<VerifyBlockResp>(
                    "VerifyBlockResp",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static VerifyBlockResp {
        static mut instance: ::protobuf::lazy::Lazy<VerifyBlockResp> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const VerifyBlockResp,
        };
        unsafe {
            instance.get(VerifyBlockResp::new)
        }
    }
}

impl ::protobuf::Clear for VerifyBlockResp {
    fn clear(&mut self) {
        self.clear_id();
        self.clear_ret();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for VerifyBlockResp {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for VerifyBlockResp {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct BlockTxHashes {
    // message fields
    pub height: u64,
    pub tx_hashes: ::protobuf::RepeatedField<::std::vec::Vec<u8>>,
    pub block_quota_limit: u64,
    pub account_quota_limit: ::protobuf::SingularPtrField<super::blockchain::AccountGasLimit>,
    pub check_quota: bool,
    pub admin_address: ::std::vec::Vec<u8>,
    pub version: u32,
    // special fields
    unknown_fields: ::protobuf::UnknownFields,
    cached_size: ::protobuf::CachedSize,
}

impl BlockTxHashes {
    pub fn new() -> BlockTxHashes {
        ::std::default::Default::default()
    }

    // uint64 height = 1;

    pub fn clear_height(&mut self) {
        self.height = 0;
    }

    // Param is passed by value, moved
    pub fn set_height(&mut self, v: u64) {
        self.height = v;
    }

    pub fn get_height(&self) -> u64 {
        self.height
    }

    // repeated bytes tx_hashes = 2;

    pub fn clear_tx_hashes(&mut self) {
        self.tx_hashes.clear();
    }

    // Param is passed by value, moved
    pub fn set_tx_hashes(&mut self, v: ::protobuf::RepeatedField<::std::vec::Vec<u8>>) {
        self.tx_hashes = v;
    }

    // Mutable pointer to the field.
    pub fn mut_tx_hashes(&mut self) -> &mut ::protobuf::RepeatedField<::std::vec::Vec<u8>> {
        &mut self.tx_hashes
    }

    // Take field
    pub fn take_tx_hashes(&mut self) -> ::protobuf::RepeatedField<::std::vec::Vec<u8>> {
        ::std::mem::replace(&mut self.tx_hashes, ::protobuf::RepeatedField::new())
    }

    pub fn get_tx_hashes(&self) -> &[::std::vec::Vec<u8>] {
        &self.tx_hashes
    }

    // uint64 block_quota_limit = 3;

    pub fn clear_block_quota_limit(&mut self) {
        self.block_quota_limit = 0;
    }

    // Param is passed by value, moved
    pub fn set_block_quota_limit(&mut self, v: u64) {
        self.block_quota_limit = v;
    }

    pub fn get_block_quota_limit(&self) -> u64 {
        self.block_quota_limit
    }

    // .AccountGasLimit account_quota_limit = 4;

    pub fn clear_account_quota_limit(&mut self) {
        self.account_quota_limit.clear();
    }

    pub fn has_account_quota_limit(&self) -> bool {
        self.account_quota_limit.is_some()
    }

    // Param is passed by value, moved
    pub fn set_account_quota_limit(&mut self, v: super::blockchain::AccountGasLimit) {
        self.account_quota_limit = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_account_quota_limit(&mut self) -> &mut super::blockchain::AccountGasLimit {
        if self.account_quota_limit.is_none() {
            self.account_quota_limit.set_default();
        }
        self.account_quota_limit.as_mut().unwrap()
    }

    // Take field
    pub fn take_account_quota_limit(&mut self) -> super::blockchain::AccountGasLimit {
        self.account_quota_limit.take().unwrap_or_else(|| super::blockchain::AccountGasLimit::new())
    }

    pub fn get_account_quota_limit(&self) -> &super::blockchain::AccountGasLimit {
        self.account_quota_limit.as_ref().unwrap_or_else(|| super::blockchain::AccountGasLimit::default_instance())
    }

    // bool check_quota = 5;

    pub fn clear_check_quota(&mut self) {
        self.check_quota = false;
    }

    // Param is passed by value, moved
    pub fn set_check_quota(&mut self, v: bool) {
        self.check_quota = v;
    }

    pub fn get_check_quota(&self) -> bool {
        self.check_quota
    }

    // bytes admin_address = 6;

    pub fn clear_admin_address(&mut self) {
        self.admin_address.clear();
    }

    // Param is passed by value, moved
    pub fn set_admin_address(&mut self, v: ::std::vec::Vec<u8>) {
        self.admin_address = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_admin_address(&mut self) -> &mut ::std::vec::Vec<u8> {
        &mut self.admin_address
    }

    // Take field
    pub fn take_admin_address(&mut self) -> ::std::vec::Vec<u8> {
        ::std::mem::replace(&mut self.admin_address, ::std::vec::Vec::new())
    }

    pub fn get_admin_address(&self) -> &[u8] {
        &self.admin_address
    }

    // uint32 version = 7;

    pub fn clear_version(&mut self) {
        self.version = 0;
    }

    // Param is passed by value, moved
    pub fn set_version(&mut self, v: u32) {
        self.version = v;
    }

    pub fn get_version(&self) -> u32 {
        self.version
    }
}

impl ::protobuf::Message for BlockTxHashes {
    fn is_initialized(&self) -> bool {
        for v in &self.account_quota_limit {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint64()?;
                    self.height = tmp;
                },
                2 => {
                    ::protobuf::rt::read_repeated_bytes_into(wire_type, is, &mut self.tx_hashes)?;
                },
                3 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint64()?;
                    self.block_quota_limit = tmp;
                },
                4 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.account_quota_limit)?;
                },
                5 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_bool()?;
                    self.check_quota = tmp;
                },
                6 => {
                    ::protobuf::rt::read_singular_proto3_bytes_into(wire_type, is, &mut self.admin_address)?;
                },
                7 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint32()?;
                    self.version = tmp;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if self.height != 0 {
            my_size += ::protobuf::rt::value_size(1, self.height, ::protobuf::wire_format::WireTypeVarint);
        }
        for value in &self.tx_hashes {
            my_size += ::protobuf::rt::bytes_size(2, &value);
        };
        if self.block_quota_limit != 0 {
            my_size += ::protobuf::rt::value_size(3, self.block_quota_limit, ::protobuf::wire_format::WireTypeVarint);
        }
        if let Some(ref v) = self.account_quota_limit.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        if self.check_quota != false {
            my_size += 2;
        }
        if !self.admin_address.is_empty() {
            my_size += ::protobuf::rt::bytes_size(6, &self.admin_address);
        }
        if self.version != 0 {
            my_size += ::protobuf::rt::value_size(7, self.version, ::protobuf::wire_format::WireTypeVarint);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream) -> ::protobuf::ProtobufResult<()> {
        if self.height != 0 {
            os.write_uint64(1, self.height)?;
        }
        for v in &self.tx_hashes {
            os.write_bytes(2, &v)?;
        };
        if self.block_quota_limit != 0 {
            os.write_uint64(3, self.block_quota_limit)?;
        }
        if let Some(ref v) = self.account_quota_limit.as_ref() {
            os.write_tag(4, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        if self.check_quota != false {
            os.write_bool(5, self.check_quota)?;
        }
        if !self.admin_address.is_empty() {
            os.write_bytes(6, &self.admin_address)?;
        }
        if self.version != 0 {
            os.write_uint32(7, self.version)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &::std::any::Any {
        self as &::std::any::Any
    }
    fn as_any_mut(&mut self) -> &mut ::std::any::Any {
        self as &mut ::std::any::Any
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<::std::any::Any> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> BlockTxHashes {
        BlockTxHashes::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint64>(
                    "height",
                    |m: &BlockTxHashes| { &m.height },
                    |m: &mut BlockTxHashes| { &mut m.height },
                ));
                fields.push(::protobuf::reflect::accessor::make_repeated_field_accessor::<_, ::protobuf::types::ProtobufTypeBytes>(
                    "tx_hashes",
                    |m: &BlockTxHashes| { &m.tx_hashes },
                    |m: &mut BlockTxHashes| { &mut m.tx_hashes },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint64>(
                    "block_quota_limit",
                    |m: &BlockTxHashes| { &m.block_quota_limit },
                    |m: &mut BlockTxHashes| { &mut m.block_quota_limit },
                ));
                fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<super::blockchain::AccountGasLimit>>(
                    "account_quota_limit",
                    |m: &BlockTxHashes| { &m.account_quota_limit },
                    |m: &mut BlockTxHashes| { &mut m.account_quota_limit },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeBool>(
                    "check_quota",
                    |m: &BlockTxHashes| { &m.check_quota },
                    |m: &mut BlockTxHashes| { &mut m.check_quota },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeBytes>(
                    "admin_address",
                    |m: &BlockTxHashes| { &m.admin_address },
                    |m: &mut BlockTxHashes| { &mut m.admin_address },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint32>(
                    "version",
                    |m: &BlockTxHashes| { &m.version },
                    |m: &mut BlockTxHashes| { &mut m.version },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<BlockTxHashes>(
                    "BlockTxHashes",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static BlockTxHashes {
        static mut instance: ::protobuf::lazy::Lazy<BlockTxHashes> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const BlockTxHashes,
        };
        unsafe {
            instance.get(BlockTxHashes::new)
        }
    }
}

impl ::protobuf::Clear for BlockTxHashes {
    fn clear(&mut self) {
        self.clear_height();
        self.clear_tx_hashes();
        self.clear_block_quota_limit();
        self.clear_account_quota_limit();
        self.clear_check_quota();
        self.clear_admin_address();
        self.clear_version();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for BlockTxHashes {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for BlockTxHashes {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct BlockTxHashesReq {
    // message fields
    pub height: u64,
    // special fields
    unknown_fields: ::protobuf::UnknownFields,
    cached_size: ::protobuf::CachedSize,
}

impl BlockTxHashesReq {
    pub fn new() -> BlockTxHashesReq {
        ::std::default::Default::default()
    }

    // uint64 height = 1;

    pub fn clear_height(&mut self) {
        self.height = 0;
    }

    // Param is passed by value, moved
    pub fn set_height(&mut self, v: u64) {
        self.height = v;
    }

    pub fn get_height(&self) -> u64 {
        self.height
    }
}

impl ::protobuf::Message for BlockTxHashesReq {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint64()?;
                    self.height = tmp;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if self.height != 0 {
            my_size += ::protobuf::rt::value_size(1, self.height, ::protobuf::wire_format::WireTypeVarint);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream) -> ::protobuf::ProtobufResult<()> {
        if self.height != 0 {
            os.write_uint64(1, self.height)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &::std::any::Any {
        self as &::std::any::Any
    }
    fn as_any_mut(&mut self) -> &mut ::std::any::Any {
        self as &mut ::std::any::Any
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<::std::any::Any> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> BlockTxHashesReq {
        BlockTxHashesReq::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint64>(
                    "height",
                    |m: &BlockTxHashesReq| { &m.height },
                    |m: &mut BlockTxHashesReq| { &mut m.height },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<BlockTxHashesReq>(
                    "BlockTxHashesReq",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static BlockTxHashesReq {
        static mut instance: ::protobuf::lazy::Lazy<BlockTxHashesReq> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const BlockTxHashesReq,
        };
        unsafe {
            instance.get(BlockTxHashesReq::new)
        }
    }
}

impl ::protobuf::Clear for BlockTxHashesReq {
    fn clear(&mut self) {
        self.clear_height();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for BlockTxHashesReq {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for BlockTxHashesReq {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct Miscellaneous {
    // message fields
    pub chain_id: u32,
    pub chain_id_v1: ::std::vec::Vec<u8>,
    // special fields
    unknown_fields: ::protobuf::UnknownFields,
    cached_size: ::protobuf::CachedSize,
}

impl Miscellaneous {
    pub fn new() -> Miscellaneous {
        ::std::default::Default::default()
    }

    // uint32 chain_id = 1;

    pub fn clear_chain_id(&mut self) {
        self.chain_id = 0;
    }

    // Param is passed by value, moved
    pub fn set_chain_id(&mut self, v: u32) {
        self.chain_id = v;
    }

    pub fn get_chain_id(&self) -> u32 {
        self.chain_id
    }

    // bytes chain_id_v1 = 2;

    pub fn clear_chain_id_v1(&mut self) {
        self.chain_id_v1.clear();
    }

    // Param is passed by value, moved
    pub fn set_chain_id_v1(&mut self, v: ::std::vec::Vec<u8>) {
        self.chain_id_v1 = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_chain_id_v1(&mut self) -> &mut ::std::vec::Vec<u8> {
        &mut self.chain_id_v1
    }

    // Take field
    pub fn take_chain_id_v1(&mut self) -> ::std::vec::Vec<u8> {
        ::std::mem::replace(&mut self.chain_id_v1, ::std::vec::Vec::new())
    }

    pub fn get_chain_id_v1(&self) -> &[u8] {
        &self.chain_id_v1
    }
}

impl ::protobuf::Message for Miscellaneous {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint32()?;
                    self.chain_id = tmp;
                },
                2 => {
                    ::protobuf::rt::read_singular_proto3_bytes_into(wire_type, is, &mut self.chain_id_v1)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if self.chain_id != 0 {
            my_size += ::protobuf::rt::value_size(1, self.chain_id, ::protobuf::wire_format::WireTypeVarint);
        }
        if !self.chain_id_v1.is_empty() {
            my_size += ::protobuf::rt::bytes_size(2, &self.chain_id_v1);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream) -> ::protobuf::ProtobufResult<()> {
        if self.chain_id != 0 {
            os.write_uint32(1, self.chain_id)?;
        }
        if !self.chain_id_v1.is_empty() {
            os.write_bytes(2, &self.chain_id_v1)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &::std::any::Any {
        self as &::std::any::Any
    }
    fn as_any_mut(&mut self) -> &mut ::std::any::Any {
        self as &mut ::std::any::Any
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<::std::any::Any> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> Miscellaneous {
        Miscellaneous::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint32>(
                    "chain_id",
                    |m: &Miscellaneous| { &m.chain_id },
                    |m: &mut Miscellaneous| { &mut m.chain_id },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeBytes>(
                    "chain_id_v1",
                    |m: &Miscellaneous| { &m.chain_id_v1 },
                    |m: &mut Miscellaneous| { &mut m.chain_id_v1 },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<Miscellaneous>(
                    "Miscellaneous",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static Miscellaneous {
        static mut instance: ::protobuf::lazy::Lazy<Miscellaneous> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const Miscellaneous,
        };
        unsafe {
            instance.get(Miscellaneous::new)
        }
    }
}

impl ::protobuf::Clear for Miscellaneous {
    fn clear(&mut self) {
        self.clear_chain_id();
        self.clear_chain_id_v1();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for Miscellaneous {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Miscellaneous {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct MiscellaneousReq {
    // special fields
    unknown_fields: ::protobuf::UnknownFields,
    cached_size: ::protobuf::CachedSize,
}

impl MiscellaneousReq {
    pub fn new() -> MiscellaneousReq {
        ::std::default::Default::default()
    }
}

impl ::protobuf::Message for MiscellaneousReq {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream) -> ::protobuf::ProtobufResult<()> {
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &::std::any::Any {
        self as &::std::any::Any
    }
    fn as_any_mut(&mut self) -> &mut ::std::any::Any {
        self as &mut ::std::any::Any
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<::std::any::Any> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> MiscellaneousReq {
        MiscellaneousReq::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let fields = ::std::vec::Vec::new();
                ::protobuf::reflect::MessageDescriptor::new::<MiscellaneousReq>(
                    "MiscellaneousReq",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static MiscellaneousReq {
        static mut instance: ::protobuf::lazy::Lazy<MiscellaneousReq> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const MiscellaneousReq,
        };
        unsafe {
            instance.get(MiscellaneousReq::new)
        }
    }
}

impl ::protobuf::Clear for MiscellaneousReq {
    fn clear(&mut self) {
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for MiscellaneousReq {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for MiscellaneousReq {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

#[derive(Clone,PartialEq,Eq,Debug,Hash)]
pub enum Ret {
    OK = 0,
    InvalidNonce = 1,
    Dup = 2,
    InvalidUntilBlock = 3,
    BadSig = 4,
    NotReady = 5,
    Busy = 6,
    BadChainId = 7,
    QuotaNotEnough = 8,
    Forbidden = 9,
    InvalidValue = 10,
    InvalidVersion = 11,
}

impl ::protobuf::ProtobufEnum for Ret {
    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<Ret> {
        match value {
            0 => ::std::option::Option::Some(Ret::OK),
            1 => ::std::option::Option::Some(Ret::InvalidNonce),
            2 => ::std::option::Option::Some(Ret::Dup),
            3 => ::std::option::Option::Some(Ret::InvalidUntilBlock),
            4 => ::std::option::Option::Some(Ret::BadSig),
            5 => ::std::option::Option::Some(Ret::NotReady),
            6 => ::std::option::Option::Some(Ret::Busy),
            7 => ::std::option::Option::Some(Ret::BadChainId),
            8 => ::std::option::Option::Some(Ret::QuotaNotEnough),
            9 => ::std::option::Option::Some(Ret::Forbidden),
            10 => ::std::option::Option::Some(Ret::InvalidValue),
            11 => ::std::option::Option::Some(Ret::InvalidVersion),
            _ => ::std::option::Option::None
        }
    }

    fn values() -> &'static [Self] {
        static values: &'static [Ret] = &[
            Ret::OK,
            Ret::InvalidNonce,
            Ret::Dup,
            Ret::InvalidUntilBlock,
            Ret::BadSig,
            Ret::NotReady,
            Ret::Busy,
            Ret::BadChainId,
            Ret::QuotaNotEnough,
            Ret::Forbidden,
            Ret::InvalidValue,
            Ret::InvalidVersion,
        ];
        values
    }

    fn enum_descriptor_static() -> &'static ::protobuf::reflect::EnumDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::EnumDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                ::protobuf::reflect::EnumDescriptor::new("Ret", file_descriptor_proto())
            })
        }
    }
}

impl ::std::marker::Copy for Ret {
}

impl ::std::default::Default for Ret {
    fn default() -> Self {
        Ret::OK
    }
}

impl ::protobuf::reflect::ProtobufValue for Ret {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Enum(self.descriptor())
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\nauth.proto\x1a\x10blockchain.proto\"\xba\x02\n\x0bVerifyTxReq\x12*\n\
    \x11valid_until_block\x18\x01\x20\x01(\x04R\x0fvalidUntilBlock\x12\x12\n\
    \x04hash\x18\x02\x20\x01(\x0cR\x04hash\x12\x1c\n\tsignature\x18\x03\x20\
    \x01(\x0cR\tsignature\x12\x1f\n\x06crypto\x18\x04\x20\x01(\x0e2\x07.Cryp\
    toR\x06crypto\x12\x17\n\x07tx_hash\x18\x05\x20\x01(\x0cR\x06txHash\x12\
    \x16\n\x06signer\x18\x06\x20\x01(\x0cR\x06signer\x12\x14\n\x05nonce\x18\
    \x07\x20\x01(\tR\x05nonce\x12\x19\n\x08chain_id\x18\x08\x20\x01(\rR\x07c\
    hainId\x12\x14\n\x05quota\x18\t\x20\x01(\x04R\x05quota\x12\x14\n\x05valu\
    e\x18\n\x20\x01(\x0cR\x05value\x12\x1e\n\x0bchain_id_v1\x18\x0b\x20\x01(\
    \x0cR\tchainIdV1\"B\n\x0eVerifyBlockReq\x12\x0e\n\x02id\x18\x01\x20\x01(\
    \x04R\x02id\x12\x20\n\x04reqs\x18\x02\x20\x03(\x0b2\x0c.VerifyTxReqR\x04\
    reqs\"9\n\x0fVerifyBlockResp\x12\x0e\n\x02id\x18\x01\x20\x01(\x04R\x02id\
    \x12\x16\n\x03ret\x18\x02\x20\x01(\x0e2\x04.RetR\x03ret\"\x92\x02\n\rBlo\
    ckTxHashes\x12\x16\n\x06height\x18\x01\x20\x01(\x04R\x06height\x12\x1b\n\
    \ttx_hashes\x18\x02\x20\x03(\x0cR\x08txHashes\x12*\n\x11block_quota_limi\
    t\x18\x03\x20\x01(\x04R\x0fblockQuotaLimit\x12@\n\x13account_quota_limit\
    \x18\x04\x20\x01(\x0b2\x10.AccountGasLimitR\x11accountQuotaLimit\x12\x1f\
    \n\x0bcheck_quota\x18\x05\x20\x01(\x08R\ncheckQuota\x12#\n\radmin_addres\
    s\x18\x06\x20\x01(\x0cR\x0cadminAddress\x12\x18\n\x07version\x18\x07\x20\
    \x01(\rR\x07version\"*\n\x10BlockTxHashesReq\x12\x16\n\x06height\x18\x01\
    \x20\x01(\x04R\x06height\"J\n\rMiscellaneous\x12\x19\n\x08chain_id\x18\
    \x01\x20\x01(\rR\x07chainId\x12\x1e\n\x0bchain_id_v1\x18\x02\x20\x01(\
    \x0cR\tchainIdV1\"\x12\n\x10MiscellaneousReq*\xbc\x01\n\x03Ret\x12\x06\n\
    \x02OK\x10\0\x12\x10\n\x0cInvalidNonce\x10\x01\x12\x07\n\x03Dup\x10\x02\
    \x12\x15\n\x11InvalidUntilBlock\x10\x03\x12\n\n\x06BadSig\x10\x04\x12\
    \x0c\n\x08NotReady\x10\x05\x12\x08\n\x04Busy\x10\x06\x12\x0e\n\nBadChain\
    Id\x10\x07\x12\x12\n\x0eQuotaNotEnough\x10\x08\x12\r\n\tForbidden\x10\t\
    \x12\x10\n\x0cInvalidValue\x10\n\x12\x12\n\x0eInvalidVersion\x10\x0bJ\
    \xc0\x13\n\x06\x12\x04\0\0?\x01\n\x08\n\x01\x0c\x12\x03\0\0\x12\n\t\n\
    \x02\x03\0\x12\x03\x02\x07\x19\n\n\n\x02\x05\0\x12\x04\x04\0\x11\x01\n\n\
    \n\x03\x05\0\x01\x12\x03\x04\x05\x08\n\x0b\n\x04\x05\0\x02\0\x12\x03\x05\
    \x04\x0b\n\x0c\n\x05\x05\0\x02\0\x01\x12\x03\x05\x04\x06\n\x0c\n\x05\x05\
    \0\x02\0\x02\x12\x03\x05\t\n\n\x0b\n\x04\x05\0\x02\x01\x12\x03\x06\x04\
    \x15\n\x0c\n\x05\x05\0\x02\x01\x01\x12\x03\x06\x04\x10\n\x0c\n\x05\x05\0\
    \x02\x01\x02\x12\x03\x06\x13\x14\n\x0b\n\x04\x05\0\x02\x02\x12\x03\x07\
    \x04\x0c\n\x0c\n\x05\x05\0\x02\x02\x01\x12\x03\x07\x04\x07\n\x0c\n\x05\
    \x05\0\x02\x02\x02\x12\x03\x07\n\x0b\n\x0b\n\x04\x05\0\x02\x03\x12\x03\
    \x08\x04\x1a\n\x0c\n\x05\x05\0\x02\x03\x01\x12\x03\x08\x04\x15\n\x0c\n\
    \x05\x05\0\x02\x03\x02\x12\x03\x08\x18\x19\n\x0b\n\x04\x05\0\x02\x04\x12\
    \x03\t\x04\x0f\n\x0c\n\x05\x05\0\x02\x04\x01\x12\x03\t\x04\n\n\x0c\n\x05\
    \x05\0\x02\x04\x02\x12\x03\t\r\x0e\n\x0b\n\x04\x05\0\x02\x05\x12\x03\n\
    \x04\x11\n\x0c\n\x05\x05\0\x02\x05\x01\x12\x03\n\x04\x0c\n\x0c\n\x05\x05\
    \0\x02\x05\x02\x12\x03\n\x0f\x10\n\x0b\n\x04\x05\0\x02\x06\x12\x03\x0b\
    \x04\r\n\x0c\n\x05\x05\0\x02\x06\x01\x12\x03\x0b\x04\x08\n\x0c\n\x05\x05\
    \0\x02\x06\x02\x12\x03\x0b\x0b\x0c\n\x0b\n\x04\x05\0\x02\x07\x12\x03\x0c\
    \x04\x13\n\x0c\n\x05\x05\0\x02\x07\x01\x12\x03\x0c\x04\x0e\n\x0c\n\x05\
    \x05\0\x02\x07\x02\x12\x03\x0c\x11\x12\n\x0b\n\x04\x05\0\x02\x08\x12\x03\
    \r\x04\x17\n\x0c\n\x05\x05\0\x02\x08\x01\x12\x03\r\x04\x12\n\x0c\n\x05\
    \x05\0\x02\x08\x02\x12\x03\r\x15\x16\n\x0b\n\x04\x05\0\x02\t\x12\x03\x0e\
    \x04\x12\n\x0c\n\x05\x05\0\x02\t\x01\x12\x03\x0e\x04\r\n\x0c\n\x05\x05\0\
    \x02\t\x02\x12\x03\x0e\x10\x11\n\x0b\n\x04\x05\0\x02\n\x12\x03\x0f\x04\
    \x16\n\x0c\n\x05\x05\0\x02\n\x01\x12\x03\x0f\x04\x10\n\x0c\n\x05\x05\0\
    \x02\n\x02\x12\x03\x0f\x13\x15\n\x0b\n\x04\x05\0\x02\x0b\x12\x03\x10\x04\
    \x18\n\x0c\n\x05\x05\0\x02\x0b\x01\x12\x03\x10\x04\x12\n\x0c\n\x05\x05\0\
    \x02\x0b\x02\x12\x03\x10\x15\x17\n\n\n\x02\x04\0\x12\x04\x13\0\x1f\x01\n\
    \n\n\x03\x04\0\x01\x12\x03\x13\x08\x13\n\x0b\n\x04\x04\0\x02\0\x12\x03\
    \x14\x04!\n\r\n\x05\x04\0\x02\0\x04\x12\x04\x14\x04\x13\x15\n\x0c\n\x05\
    \x04\0\x02\0\x05\x12\x03\x14\x04\n\n\x0c\n\x05\x04\0\x02\0\x01\x12\x03\
    \x14\x0b\x1c\n\x0c\n\x05\x04\0\x02\0\x03\x12\x03\x14\x1f\x20\n\x0b\n\x04\
    \x04\0\x02\x01\x12\x03\x15\x04\x13\n\r\n\x05\x04\0\x02\x01\x04\x12\x04\
    \x15\x04\x14!\n\x0c\n\x05\x04\0\x02\x01\x05\x12\x03\x15\x04\t\n\x0c\n\
    \x05\x04\0\x02\x01\x01\x12\x03\x15\n\x0e\n\x0c\n\x05\x04\0\x02\x01\x03\
    \x12\x03\x15\x11\x12\n\x0b\n\x04\x04\0\x02\x02\x12\x03\x16\x04\x18\n\r\n\
    \x05\x04\0\x02\x02\x04\x12\x04\x16\x04\x15\x13\n\x0c\n\x05\x04\0\x02\x02\
    \x05\x12\x03\x16\x04\t\n\x0c\n\x05\x04\0\x02\x02\x01\x12\x03\x16\n\x13\n\
    \x0c\n\x05\x04\0\x02\x02\x03\x12\x03\x16\x16\x17\n\x0b\n\x04\x04\0\x02\
    \x03\x12\x03\x17\x04\x16\n\r\n\x05\x04\0\x02\x03\x04\x12\x04\x17\x04\x16\
    \x18\n\x0c\n\x05\x04\0\x02\x03\x06\x12\x03\x17\x04\n\n\x0c\n\x05\x04\0\
    \x02\x03\x01\x12\x03\x17\x0b\x11\n\x0c\n\x05\x04\0\x02\x03\x03\x12\x03\
    \x17\x14\x15\n\x0b\n\x04\x04\0\x02\x04\x12\x03\x18\x04\x16\n\r\n\x05\x04\
    \0\x02\x04\x04\x12\x04\x18\x04\x17\x16\n\x0c\n\x05\x04\0\x02\x04\x05\x12\
    \x03\x18\x04\t\n\x0c\n\x05\x04\0\x02\x04\x01\x12\x03\x18\n\x11\n\x0c\n\
    \x05\x04\0\x02\x04\x03\x12\x03\x18\x14\x15\n.\n\x04\x04\0\x02\x05\x12\
    \x03\x19\x04\x15\"!\x20public\x20key\x20only\x20set\x20in\x20BlockReq\n\
    \n\r\n\x05\x04\0\x02\x05\x04\x12\x04\x19\x04\x18\x16\n\x0c\n\x05\x04\0\
    \x02\x05\x05\x12\x03\x19\x04\t\n\x0c\n\x05\x04\0\x02\x05\x01\x12\x03\x19\
    \n\x10\n\x0c\n\x05\x04\0\x02\x05\x03\x12\x03\x19\x13\x14\n\x0b\n\x04\x04\
    \0\x02\x06\x12\x03\x1a\x04\x15\n\r\n\x05\x04\0\x02\x06\x04\x12\x04\x1a\
    \x04\x19\x15\n\x0c\n\x05\x04\0\x02\x06\x05\x12\x03\x1a\x04\n\n\x0c\n\x05\
    \x04\0\x02\x06\x01\x12\x03\x1a\x0b\x10\n\x0c\n\x05\x04\0\x02\x06\x03\x12\
    \x03\x1a\x13\x14\n\x0b\n\x04\x04\0\x02\x07\x12\x03\x1b\x04\x18\n\r\n\x05\
    \x04\0\x02\x07\x04\x12\x04\x1b\x04\x1a\x15\n\x0c\n\x05\x04\0\x02\x07\x05\
    \x12\x03\x1b\x04\n\n\x0c\n\x05\x04\0\x02\x07\x01\x12\x03\x1b\x0b\x13\n\
    \x0c\n\x05\x04\0\x02\x07\x03\x12\x03\x1b\x16\x17\n\x0b\n\x04\x04\0\x02\
    \x08\x12\x03\x1c\x04\x15\n\r\n\x05\x04\0\x02\x08\x04\x12\x04\x1c\x04\x1b\
    \x18\n\x0c\n\x05\x04\0\x02\x08\x05\x12\x03\x1c\x04\n\n\x0c\n\x05\x04\0\
    \x02\x08\x01\x12\x03\x1c\x0b\x10\n\x0c\n\x05\x04\0\x02\x08\x03\x12\x03\
    \x1c\x13\x14\n\x0b\n\x04\x04\0\x02\t\x12\x03\x1d\x04\x15\n\r\n\x05\x04\0\
    \x02\t\x04\x12\x04\x1d\x04\x1c\x15\n\x0c\n\x05\x04\0\x02\t\x05\x12\x03\
    \x1d\x04\t\n\x0c\n\x05\x04\0\x02\t\x01\x12\x03\x1d\n\x0f\n\x0c\n\x05\x04\
    \0\x02\t\x03\x12\x03\x1d\x12\x14\n\x0b\n\x04\x04\0\x02\n\x12\x03\x1e\x04\
    \x1b\n\r\n\x05\x04\0\x02\n\x04\x12\x04\x1e\x04\x1d\x15\n\x0c\n\x05\x04\0\
    \x02\n\x05\x12\x03\x1e\x04\t\n\x0c\n\x05\x04\0\x02\n\x01\x12\x03\x1e\n\
    \x15\n\x0c\n\x05\x04\0\x02\n\x03\x12\x03\x1e\x18\x1a\n\n\n\x02\x04\x01\
    \x12\x04!\0$\x01\n\n\n\x03\x04\x01\x01\x12\x03!\x08\x16\n\x0b\n\x04\x04\
    \x01\x02\0\x12\x03\"\x04\x12\n\r\n\x05\x04\x01\x02\0\x04\x12\x04\"\x04!\
    \x18\n\x0c\n\x05\x04\x01\x02\0\x05\x12\x03\"\x04\n\n\x0c\n\x05\x04\x01\
    \x02\0\x01\x12\x03\"\x0b\r\n\x0c\n\x05\x04\x01\x02\0\x03\x12\x03\"\x10\
    \x11\n\x0b\n\x04\x04\x01\x02\x01\x12\x03#\x04\"\n\x0c\n\x05\x04\x01\x02\
    \x01\x04\x12\x03#\x04\x0c\n\x0c\n\x05\x04\x01\x02\x01\x06\x12\x03#\r\x18\
    \n\x0c\n\x05\x04\x01\x02\x01\x01\x12\x03#\x19\x1d\n\x0c\n\x05\x04\x01\
    \x02\x01\x03\x12\x03#\x20!\n\n\n\x02\x04\x02\x12\x04&\0)\x01\n\n\n\x03\
    \x04\x02\x01\x12\x03&\x08\x17\n\x0b\n\x04\x04\x02\x02\0\x12\x03'\x04\x12\
    \n\r\n\x05\x04\x02\x02\0\x04\x12\x04'\x04&\x19\n\x0c\n\x05\x04\x02\x02\0\
    \x05\x12\x03'\x04\n\n\x0c\n\x05\x04\x02\x02\0\x01\x12\x03'\x0b\r\n\x0c\n\
    \x05\x04\x02\x02\0\x03\x12\x03'\x10\x11\n\x0b\n\x04\x04\x02\x02\x01\x12\
    \x03(\x04\x10\n\r\n\x05\x04\x02\x02\x01\x04\x12\x04(\x04'\x12\n\x0c\n\
    \x05\x04\x02\x02\x01\x06\x12\x03(\x04\x07\n\x0c\n\x05\x04\x02\x02\x01\
    \x01\x12\x03(\x08\x0b\n\x0c\n\x05\x04\x02\x02\x01\x03\x12\x03(\x0e\x0f\n\
    \n\n\x02\x04\x03\x12\x04+\03\x01\n\n\n\x03\x04\x03\x01\x12\x03+\x08\x15\
    \n\x0b\n\x04\x04\x03\x02\0\x12\x03,\x04\x16\n\r\n\x05\x04\x03\x02\0\x04\
    \x12\x04,\x04+\x17\n\x0c\n\x05\x04\x03\x02\0\x05\x12\x03,\x04\n\n\x0c\n\
    \x05\x04\x03\x02\0\x01\x12\x03,\x0b\x11\n\x0c\n\x05\x04\x03\x02\0\x03\
    \x12\x03,\x14\x15\n\x0b\n\x04\x04\x03\x02\x01\x12\x03-\x04!\n\x0c\n\x05\
    \x04\x03\x02\x01\x04\x12\x03-\x04\x0c\n\x0c\n\x05\x04\x03\x02\x01\x05\
    \x12\x03-\r\x12\n\x0c\n\x05\x04\x03\x02\x01\x01\x12\x03-\x13\x1c\n\x0c\n\
    \x05\x04\x03\x02\x01\x03\x12\x03-\x1f\x20\n\x0b\n\x04\x04\x03\x02\x02\
    \x12\x03.\x04!\n\r\n\x05\x04\x03\x02\x02\x04\x12\x04.\x04-!\n\x0c\n\x05\
    \x04\x03\x02\x02\x05\x12\x03.\x04\n\n\x0c\n\x05\x04\x03\x02\x02\x01\x12\
    \x03.\x0b\x1c\n\x0c\n\x05\x04\x03\x02\x02\x03\x12\x03.\x1f\x20\n\x0b\n\
    \x04\x04\x03\x02\x03\x12\x03/\x04,\n\r\n\x05\x04\x03\x02\x03\x04\x12\x04\
    /\x04.!\n\x0c\n\x05\x04\x03\x02\x03\x06\x12\x03/\x04\x13\n\x0c\n\x05\x04\
    \x03\x02\x03\x01\x12\x03/\x14'\n\x0c\n\x05\x04\x03\x02\x03\x03\x12\x03/*\
    +\n\x0b\n\x04\x04\x03\x02\x04\x12\x030\x04\x19\n\r\n\x05\x04\x03\x02\x04\
    \x04\x12\x040\x04/,\n\x0c\n\x05\x04\x03\x02\x04\x05\x12\x030\x04\x08\n\
    \x0c\n\x05\x04\x03\x02\x04\x01\x12\x030\t\x14\n\x0c\n\x05\x04\x03\x02\
    \x04\x03\x12\x030\x17\x18\n\x0b\n\x04\x04\x03\x02\x05\x12\x031\x04\x1c\n\
    \r\n\x05\x04\x03\x02\x05\x04\x12\x041\x040\x19\n\x0c\n\x05\x04\x03\x02\
    \x05\x05\x12\x031\x04\t\n\x0c\n\x05\x04\x03\x02\x05\x01\x12\x031\n\x17\n\
    \x0c\n\x05\x04\x03\x02\x05\x03\x12\x031\x1a\x1b\n\x0b\n\x04\x04\x03\x02\
    \x06\x12\x032\x04\x17\n\r\n\x05\x04\x03\x02\x06\x04\x12\x042\x041\x1c\n\
    \x0c\n\x05\x04\x03\x02\x06\x05\x12\x032\x04\n\n\x0c\n\x05\x04\x03\x02\
    \x06\x01\x12\x032\x0b\x12\n\x0c\n\x05\x04\x03\x02\x06\x03\x12\x032\x15\
    \x16\n\n\n\x02\x04\x04\x12\x045\07\x01\n\n\n\x03\x04\x04\x01\x12\x035\
    \x08\x18\n\x0b\n\x04\x04\x04\x02\0\x12\x036\x04\x16\n\r\n\x05\x04\x04\
    \x02\0\x04\x12\x046\x045\x1a\n\x0c\n\x05\x04\x04\x02\0\x05\x12\x036\x04\
    \n\n\x0c\n\x05\x04\x04\x02\0\x01\x12\x036\x0b\x11\n\x0c\n\x05\x04\x04\
    \x02\0\x03\x12\x036\x14\x15\n\n\n\x02\x04\x05\x12\x049\0<\x01\n\n\n\x03\
    \x04\x05\x01\x12\x039\x08\x15\n\x0b\n\x04\x04\x05\x02\0\x12\x03:\x04\x18\
    \n\r\n\x05\x04\x05\x02\0\x04\x12\x04:\x049\x17\n\x0c\n\x05\x04\x05\x02\0\
    \x05\x12\x03:\x04\n\n\x0c\n\x05\x04\x05\x02\0\x01\x12\x03:\x0b\x13\n\x0c\
    \n\x05\x04\x05\x02\0\x03\x12\x03:\x16\x17\n\x0b\n\x04\x04\x05\x02\x01\
    \x12\x03;\x04\x1a\n\r\n\x05\x04\x05\x02\x01\x04\x12\x04;\x04:\x18\n\x0c\
    \n\x05\x04\x05\x02\x01\x05\x12\x03;\x04\t\n\x0c\n\x05\x04\x05\x02\x01\
    \x01\x12\x03;\n\x15\n\x0c\n\x05\x04\x05\x02\x01\x03\x12\x03;\x18\x19\n\n\
    \n\x02\x04\x06\x12\x04>\0?\x01\n\n\n\x03\x04\x06\x01\x12\x03>\x08\x18b\
    \x06proto3\
";

static mut file_descriptor_proto_lazy: ::protobuf::lazy::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::lazy::Lazy {
    lock: ::protobuf::lazy::ONCE_INIT,
    ptr: 0 as *const ::protobuf::descriptor::FileDescriptorProto,
};

fn parse_descriptor_proto() -> ::protobuf::descriptor::FileDescriptorProto {
    ::protobuf::parse_from_bytes(file_descriptor_proto_data).unwrap()
}

pub fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    unsafe {
        file_descriptor_proto_lazy.get(|| {
            parse_descriptor_proto()
        })
    }
}
