[package]
name = "pubsub_zeromq"
version = "0.1.0"
authors = ["Cryptape Technologies <contact@cryptape.com>"]

[dependencies.zmq]
version = "0.8"
default-features = false
features = []

[dependencies]
logger = { path = "../logger" }
crossbeam-channel = "0.3.8"
