[package]
name = "cita-crypto-trait"
version = "0.1.0"
authors = ["Cryptape Technologies <contact@cryptape.com>"]
license = "Apache-2.0"
edition = "2018"

[dependencies]
cita-types = { path = "../cita-types" }
