[package]
name = "cita-common-benches"
version = "0.1.0"
authors = ["Rivtower Technologies <contact@rivtower.com>"]
license = "Apache-2.0"
edition = "2024"

[dependencies]
rand = "0.9"

[dev-dependencies]
criterion = "0.8"
tiny-keccak = { version = "2.0", features = ["keccak"] }
blake2b = { path = "../blake2b" }
secp256k1 = { version = "0.31", features = ["rand"] }
sodiumoxide = "0.2"
libsm = "0.6"

[[bench]]
name = "hash-algos"
harness = false

[[bench]]
name = "sign-algos"
harness = false
