[package]
name = "panic_hook"
version = "0.0.1"
authors = ["Cryptape Technologies <contact@cryptape.com>"]
license = "Apache-2.0"
edition = "2018"

[dependencies]
backtrace = "0.3"
cita-logger = "0.1.0"
